const icons={grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',box:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><path d="m3.3 7 8.7 5 8.7-5M12 22V12"/>',bag:'<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4zM3 6h18M16 10a4 4 0 0 1-8 0"/>',truck:'<path d="M10 17h4V5H2v12h3m9-7h4l4 4v3h-3M7.5 20a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm9 0a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.09 14H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.63h.01A1.7 1.7 0 0 0 10 3.09V3a2 2 0 1 1 4 0v.09A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.37 9v.01A1.7 1.7 0 0 0 20.91 10H21a2 2 0 1 1 0 4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',wallet:'<path d="M20 7V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v12H5a3 3 0 0 1-3-3V6M16 13h2"/>',trend:'<path d="m3 17 6-6 4 4 8-8M14 7h7v7"/>',layers:'<path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 17l9 5 9-5"/>',alert:'<path d="M10.3 2.8 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.8a2 2 0 0 0-3.4 0ZM12 9v4M12 17h.01"/>',tag:'<path d="M20.6 13.6 11 23.2 1.8 14V2.8H13l7.6 7.6a2.3 2.3 0 0 1 0 3.2Z"/><circle cx="7" cy="8" r="1"/>',check:'<path d="m20 6-11 11-5-5"/>',spark:'<path d="m12 3-1.6 4.4L6 9l4.4 1.6L12 15l1.6-4.4L18 9l-4.4-1.6L12 3ZM5 16l-.8 2.2L2 19l2.2.8L5 22l.8-2.2L8 19l-2.2-.8L5 16Z"/>'};
Object.assign(icons,{upload:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M17 8l-5-5-5 5M12 3v12"/>',edit:'<path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>'});
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});

let products=[],importRows=[],users=[],orders=[],orderItems=[],session=JSON.parse(localStorage.getItem('tecnoland-session')||'null'),productImages=[],productSort={key:'createdAt',direction:'desc'},orderFilters={query:'',from:'',to:''};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',currencyDisplay:'narrowSymbol'}).format(n);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function api(path,options={}){const headers={'Content-Type':'application/json',...(session?.token?{Authorization:`Bearer ${session.token}`}:{}) ,...(options.headers||{})};const response=await fetch(`/api${path}`,{...options,headers});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'No fue posible guardar los cambios');return response.json()}
function setSession(next){session=next; if(next)localStorage.setItem('tecnoland-session',JSON.stringify(next)); else localStorage.removeItem('tecnoland-session')}
function showLogin(){ $('#loginModal').hidden=false }
function hideLogin(){ $('#loginModal').hidden=true }
async function loadProducts(){
 if(!session?.token){showLogin();return}
 const previous=JSON.parse(localStorage.getItem('tecnoland-products')||localStorage.getItem('novatech-products')||'null');
 if(previous?.length&&!localStorage.getItem('tecnoland-server-migration')){await api('/products/import',{method:'POST',body:JSON.stringify({products:previous})});localStorage.setItem('tecnoland-server-migration','completed')}
 products=await api('/products');populateCategories();render();
 await loadUsers().catch(()=>{});
 await loadOrders().catch(()=>{});
}
async function loadUsers(){users=await api('/users');renderUsers()}
async function loadOrders(){orders=await api('/orders');renderOrders()}
function renderUsers(){const list=$('#usersList');if(!list)return;list.innerHTML=users.map(user=>`<div class="user-row"><div><strong>${escapeHtml(user.fullName||user.full_name)}</strong><small>@${escapeHtml(user.username)} · ${escapeHtml(user.role)}</small></div><button class="secondary-button" data-toggle-user="${user.id}">${user.active?'Desactivar':'Activar'}</button></div>`).join('')||'<p>No hay usuarios.</p>'}
function renderPhotoPreview(filesOrUrls=[]){const grid=$('#photoPreviewGrid');if(!grid)return;grid.innerHTML=filesOrUrls.map((item,index)=>`<figure class="photo-card"><img src="${escapeHtml(item.url||item)}" alt="Foto ${index+1}"><button type="button" data-remove-photo="${index}">×</button></figure>`).join('')}
function setSection(section){$('#inventorySection').hidden=section!=='inventory';$('#ordersSection').hidden=section!=='orders';$('#inventoryNav').classList.toggle('active',section==='inventory');$('#ordersNav').classList.toggle('active',section==='orders');if(section==='orders'){renderOrderForm();loadOrders().catch(()=>{});}}
function openOrders(){setSection('orders')}
function renderOrderForm(){const select=$('#orderItemProduct');if(!select)return;const availableProducts=products.filter(product=>product.stock>0);select.innerHTML=availableProducts.map(product=>`<option value="${product.id}">${escapeHtml(product.name)} · ${escapeHtml(product.supplierSku||product.sku)} · ${escapeHtml(product.productColor||'Sin especificar')} · ${money(product.price)} · stock ${product.stock}</option>`).join('')||'<option value="">No hay productos con stock</option>';$('#orderItemsTable').innerHTML=orderItems.map((item,index)=>{const product=products.find(p=>p.id===item.productId);return `<tr><td><strong>${escapeHtml(product?.name||item.productName)}</strong><small>SKU ${escapeHtml(product?.supplierSku||product?.sku||item.sku)}</small></td><td>${item.quantity}</td><td>${money(item.unitPrice)}</td><td>${money(item.subtotal)}</td><td><button class="row-action danger" data-order-remove="${index}">×</button></td></tr>`}).join('')||'<tr><td colspan="5">Agrega productos al pedido.</td></tr>';const subtotal=orderItems.reduce((sum,item)=>sum+item.subtotal,0),cost=orderItems.reduce((sum,item)=>sum+item.unitCost*item.quantity,0),discount=Number($('#orderDiscount').value||0),total=Math.max(0,subtotal-discount),margin=total-cost;$('#orderProductCount').textContent=`${orderItems.length} item${orderItems.length===1?'':'s'} seleccionados`;$('#orderSubtotal').textContent=money(subtotal);$('#orderCost').textContent=money(cost);$('#orderMargin').textContent=money(margin);$('#orderTotal').textContent=money(total)}
function orderVisible(order){const q=orderFilters.query.trim().toLowerCase();const created=new Date(order.createdAt);const from=orderFilters.from?new Date(`${orderFilters.from}T00:00:00`):null;const to=orderFilters.to?new Date(`${orderFilters.to}T23:59:59`):null;const match=!q||`${order.orderNumber} ${order.customerName} ${order.status}`.toLowerCase().includes(q);return match&&(!from||created>=from)&&(!to||created<=to)}
function renderOrders(){const visible=orders.filter(orderVisible);const row=order=>`<tr><td>${escapeHtml(order.orderNumber)}</td><td>${escapeHtml(order.customerName)}</td><td>${escapeHtml(order.status)}</td><td>${money(order.total)}</td><td>${money(order.marginTotal)}</td><td>${new Date(order.createdAt).toLocaleString('es-GT')}</td><td><button class="row-action danger" data-order-delete="${order.id}" aria-label="Eliminar pedido">Eliminar</button></td></tr>`;$('#ordersTable').innerHTML=orders.slice(0,20).map(row).join('')||'<tr><td colspan="7">Todavía no hay pedidos.</td></tr>';$('#allOrdersTable').innerHTML=visible.map(row).join('')||'<tr><td colspan="7">No hay pedidos con esos filtros.</td></tr>'}

function populateCategories(){const current=$('#categoryFilter').value;const categories=[...new Set(products.map(p=>p.category))].sort();$('#categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+categories.map(c=>`<option value="${c}">${c}</option>`).join('');$('#categoryFilter').value=categories.includes(current)?current:'all'}
function filtered(){const q=[$('#searchInput')?.value||'',$('#productSearch')?.value||''].join(' ').toLowerCase().trim(),cat=$('#categoryFilter').value,status=$('#stockFilter').value;return products.filter(p=>{const match=!q||`${p.name} ${p.sku} ${p.supplierSku||''} ${p.internalSku||''} ${p.category} ${p.productColor||''}`.toLowerCase().includes(q);const catMatch=cat==='all'||p.category===cat;const stockMatch=status==='all'||(status==='low'&&p.stock>0&&p.stock<=p.threshold)||(status==='available'&&p.stock>p.threshold)||(status==='out'&&p.stock===0);return match&&catMatch&&stockMatch})}
function render(){ 
 const sortedProducts=[...products].sort((a,b)=>{const key=productSort.key;const dir=productSort.direction==='asc'?1:-1;const value=(product)=>{if(key==='margin')return (product.price||0)-(product.cost||0);if(key==='inventoryValue')return (product.cost||0)*(product.stock||0);if(key==='supplierSku')return product.supplierSku||product.sku||'';if(key==='internalSku')return product.internalSku||product.sku||'';return product[key]??''};const av=value(a),bv=value(b);if(typeof av==='string'||typeof bv==='string')return String(av).localeCompare(String(bv),'es')*dir;return (av-bv)*dir;});
 const totalCost=products.reduce((s,p)=>s+p.cost*p.stock,0),retail=products.reduce((s,p)=>s+p.price*p.stock,0),margin=retail-totalCost,units=products.reduce((s,p)=>s+p.stock,0),low=products.filter(p=>p.stock<=p.threshold).length;
 $('#inventoryCost').textContent=money(totalCost);$('#potentialMargin').textContent=money(margin);$('#marginPercent').textContent=`${retail?Math.round(margin/retail*100):0}% de rentabilidad estimada`;$('#totalUnits').textContent=units.toLocaleString();$('#lowStock').textContent=low;$('#retailValue').textContent=money(retail);$('#activeProducts').textContent=products.length;$('#navStockBadge').textContent=low;
 const list=filtered();$('#resultCount').textContent=`${list.length} producto${list.length===1?'':'s'} en el catálogo`;$('#footerCount').textContent=`Mostrando ${list.length} de ${products.length} productos`;$('#emptyState').hidden=list.length>0;
 $('#productTable').innerHTML=sortedProducts.map(p=>{const unit=p.price-p.cost,percent=p.price?unit/p.price*100:0,isLow=p.stock<=p.threshold,thumb=p.images?.[0]?.url||p.images?.[0]||'';return `<tr><td><div class="product-cell"><div class="product-thumb ${thumb?'with-image':''}" style="--thumb:${p.themeColor||'#e8ecf5'}">${thumb?`<img src="${escapeHtml(thumb)}" alt="${escapeHtml(p.name)}">`:escapeHtml(p.emoji||'📦')}</div><div class="product-info"><strong>${escapeHtml(p.name)}</strong></div></div></td><td>${escapeHtml(p.supplierSku||p.sku)}</td><td>${escapeHtml(p.internalSku||p.sku)}</td><td><span class="category-pill">${escapeHtml(p.category)}</span></td><td>${escapeHtml(p.productColor||'Sin especificar')}</td><td>${money(p.cost)}</td><td class="price">${money(p.price)}</td><td><div class="margin"><strong>+${money(unit)}</strong><small>${percent.toFixed(1)}%</small></div></td><td>${p.stock}${isLow?` <span class="stock-label">${p.stock?'BAJO':'AGOTADO'}</span>`:''}</td><td class="price">${money(p.cost*p.stock)}</td><td><div class="row-actions"><button class="row-action" data-edit="${p.id}" aria-label="Editar ${escapeHtml(p.name)}"><span data-row-icon="edit"></span></button><button class="row-action danger" data-delete="${p.id}" aria-label="Eliminar ${escapeHtml(p.name)}"><span data-row-icon="trash"></span></button></div></td></tr>`}).join('');
 document.querySelectorAll('[data-row-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[el.dataset.rowIcon]}</svg>`});
}
function openModal(product){$('#productForm').reset();$('#productId').value=product?.id||'';productImages=(product?.images||[]).map(image=>typeof image==='string'?image:image.url);$('#modalTitle').textContent=product?'Editar producto':'Nuevo producto';if(product){$('#productName').value=product.name;$('#productSku').value=product.supplierSku||product.sku;$('#productInternalSku').value=product.internalSku||product.sku;$('#productCategory').value=product.category;$('#productColor').value=product.productColor||'';$('#productCost').value=product.cost;$('#productPrice').value=product.price;$('#productStock').value=product.stock;$('#productThreshold').value=product.threshold;$('#productDescription').value=product.description||''}else {$('#productThreshold').value=5;$('#productInternalSku').value='Se generará automáticamente';}renderPhotoPreview(productImages);updateFormMargin();$('#productModal').hidden=false;setTimeout(()=>$('#productName').focus(),20)}
function closeModal(){ $('#productModal').hidden=true }
function updateFormMargin(){const c=Number($('#productCost').value),p=Number($('#productPrice').value),m=p-c;$('#formMargin').textContent=`${money(m)} (${p?(m/p*100).toFixed(1):0}%)`}
function toast(title='Producto guardado',detail='El inventario se actualizó correctamente.'){const t=$('#toast');t.querySelector('strong').textContent=title;t.querySelector('small').textContent=detail;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function closeImportModal(){ $('#importModal').hidden=true;$('#inventoryFile').value='';importRows=[] }
function openUsersModal(){ $('#usersModal').hidden=false; loadUsers().catch(error=>alert(error.message)) }
function closeUsersModal(){ $('#usersModal').hidden=true }
function openPasswordModal(){ $('#passwordModal').hidden=false }
function closePasswordModal(){ $('#passwordModal').hidden=true }
function openOrderItemModal(){ $('#orderItemModal').hidden=false; renderOrderForm() }
function closeOrderItemModal(){ $('#orderItemModal').hidden=true }
function updateSortIndicators(){document.querySelectorAll('[data-sort]').forEach(th=>{th.dataset.active=th.dataset.sort===productSort.key?'true':'false'})}
const normalizeHeader=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases={sku:['sku','codigo','codigoproducto'],name:['producto','nombre','nombreproducto'],category:['categoria'],productColor:['color'],cost:['costo','costounitario','costogtq'],price:['precio','precioventa','pvp','preciogtq'],stock:['stock','cantidad','existencia'],threshold:['alerta','stockminimo','alertastockbajo'],description:['descripcion']};
function numericValue(value){if(typeof value==='number')return value;let text=String(value??'').replace(/[Q$\s]/g,'');if(text.includes(',')&&text.includes('.'))text=text.replaceAll(',','');else if(text.includes(','))text=text.replace(',','.');return Number(text)}
function valueByAlias(row,key){const found=Object.entries(row).find(([header])=>aliases[key].includes(normalizeHeader(header)));return found?.[1]??''}
async function parseInventoryFile(file){
 if(file.size>5*1024*1024)throw new Error('El archivo supera el máximo de 5 MB.');
 let rawRows=[];
 if(file.name.toLowerCase().endsWith('.csv')){const rows=parseCsv(await file.text()),headers=rows.shift()||[];rawRows=rows.filter(row=>row.some(value=>String(value).trim())).map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]??''])))}
 else{if(!window.ExcelJS)throw new Error('No se pudo cargar el lector de Excel. Intenta nuevamente.');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)throw new Error('El Excel no contiene hojas.');const headers=sheet.getRow(1).values.slice(1).map(String);for(let rowNumber=2;rowNumber<=sheet.rowCount;rowNumber++){const values=sheet.getRow(rowNumber).values.slice(1).map(value=>value?.result??value?.text??value??'');if(values.some(value=>String(value).trim()))rawRows.push(Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])))} }
 if(!rawRows.length)throw new Error('El archivo no contiene productos.');if(rawRows.length>1000)throw new Error('El archivo supera el máximo de 1,000 productos.');
 const seen=new Set();return rawRows.map((row,index)=>{const product={sku:String(valueByAlias(row,'sku')).trim().toUpperCase(),name:String(valueByAlias(row,'name')).trim(),category:String(valueByAlias(row,'category')||'Sin categoría').trim(),productColor:String(valueByAlias(row,'productColor')||'Sin especificar').trim(),cost:numericValue(valueByAlias(row,'cost')),price:numericValue(valueByAlias(row,'price')),stock:numericValue(valueByAlias(row,'stock')),threshold:numericValue(valueByAlias(row,'threshold')||5),description:String(valueByAlias(row,'description')).trim()};const errors=[];if(!product.sku)errors.push('Falta SKU');if(!product.name)errors.push('Falta producto');for(const field of ['cost','price','stock','threshold'])if(!Number.isFinite(product[field])||product[field]<0)errors.push(`${field} inválido`);if(seen.has(product.sku)&&product.sku)errors.push('SKU duplicado');seen.add(product.sku);product.stock=Math.floor(product.stock);product.threshold=Math.floor(product.threshold);return {row:index+2,product,errors,action:products.some(item=>item.sku===product.sku)?'Actualizar':'Crear'}})}
function parseCsv(text){const rows=[];let row=[],value='',quoted=false;for(let index=0;index<text.length;index++){const char=text[index];if(char==='"'){if(quoted&&text[index+1]==='"'){value+='"';index+=1}else quoted=!quoted}else if(char===','&&!quoted){row.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[index+1]==='\n')index+=1;row.push(value);rows.push(row);row=[];value=''}else value+=char}if(value||row.length){row.push(value);rows.push(row)}if(rows[0]?.[0])rows[0][0]=rows[0][0].replace(/^\ufeff/,'');return rows}
function showImportPreview(rows,fileName){importRows=rows;const valid=rows.filter(row=>!row.errors.length),errors=rows.length-valid.length,updates=valid.filter(row=>row.action==='Actualizar').length;$('#previewSummary').innerHTML=`<span class="summary-pill">${escapeHtml(fileName)}</span><span class="summary-pill">${valid.length-updates} nuevos</span><span class="summary-pill">${updates} actualizaciones</span>${errors?`<span class="summary-pill error">${errors} con error</span>`:''}`;$('#previewTable').innerHTML=rows.slice(0,50).map(item=>`<tr><td>${item.row}</td><td>${escapeHtml(item.product.sku||'—')}</td><td>${escapeHtml(item.product.name||'—')}</td><td>${item.action}</td><td class="import-status ${item.errors.length?'error':'ok'}">${item.errors.length?escapeHtml(item.errors.join(', ')):'Lista'}</td></tr>`).join('');$('#importPreview').hidden=false;$('#confirmImport').disabled=!valid.length}
$('#addProductButton').addEventListener('click',()=>openModal());$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);$('#productModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeImportModal();closeUsersModal();closePasswordModal();closeOrderItemModal();hideLogin()}});
['searchInput','productSearch','categoryFilter','stockFilter'].forEach(id=>$('#'+id)?.addEventListener(id.includes('search')?'input':'change',render));['productCost','productPrice'].forEach(id=>$('#'+id).addEventListener('input',updateFormMargin));
$('#productTable').addEventListener('click',async e=>{const adjust=e.target.closest('[data-adjust]'),edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]');if(adjust){adjust.disabled=true;try{const updated=await api(`/products/${adjust.dataset.id}/stock`,{method:'PATCH',body:JSON.stringify({adjustment:Number(adjust.dataset.adjust)})});const index=products.findIndex(p=>p.id===updated.id);products[index]=updated;render()}catch(error){alert(error.message)}}if(edit)openModal(products.find(x=>x.id===Number(edit.dataset.edit)));if(remove){const product=products.find(x=>x.id===Number(remove.dataset.delete));if(confirm(`¿Eliminar “${product.name}”? Esta acción quedará registrada en el historial.`)){remove.disabled=true;try{await api(`/products/${product.id}`,{method:'DELETE'});products=products.filter(item=>item.id!==product.id);populateCategories();render();toast('Producto eliminado',`${product.name} se retiró del inventario.`)}catch(error){alert(error.message)}}}});
document.querySelectorAll('[data-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.sort;productSort={key,direction:productSort.key===key&&productSort.direction==='asc'?'desc':'asc'};updateSortIndicators();render()}));
$('#productPhotos').addEventListener('change',async e=>{const files=[...e.target.files||[]];const urls=await Promise.all(files.map(file=>new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})));productImages=[...productImages,...urls];renderPhotoPreview(productImages);e.target.value='';});
$('#photoPreviewGrid').addEventListener('click',e=>{const remove=e.target.closest('[data-remove-photo]');if(!remove)return;productImages=productImages.filter((_,index)=>index!==Number(remove.dataset.removePhoto));renderPhotoPreview(productImages);});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#productId').value),existing=products.find(p=>p.id===id);const data={name:$('#productName').value.trim(),sku:$('#productSku').value.trim().toUpperCase(),category:$('#productCategory').value.trim(),productColor:$('#productColor').value.trim(),cost:Number($('#productCost').value),price:Number($('#productPrice').value),stock:Number($('#productStock').value),threshold:Number($('#productThreshold').value),description:$('#productDescription').value.trim(),emoji:existing?.emoji||'📦',themeColor:existing?.themeColor||'#e8ecf5',images:productImages};try{const saved=await api(existing?`/products/${id}`:'/products',{method:existing?'PUT':'POST',body:JSON.stringify(data)});if(existing)products[products.findIndex(p=>p.id===id)]=saved;else products.unshift(saved);populateCategories();render();closeModal();toast()}catch(error){alert(error.message)}});
$('#exportButton').addEventListener('click',()=>{const rows=[['SKU','Producto','Categoría','Color','Costo (GTQ)','Precio (GTQ)','Stock'],...products.map(p=>[p.sku,p.name,p.category,p.productColor,p.cost,p.price,p.stock])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='inventario-tecnoland.csv';a.click();URL.revokeObjectURL(a.href)});
$('#importButton').addEventListener('click',()=>{$('#importModal').hidden=false;$('#importPreview').hidden=true;$('#confirmImport').disabled=true});$('#chooseFileButton').addEventListener('click',()=>$('#inventoryFile').click());$('#closeImportModal').addEventListener('click',closeImportModal);$('#cancelImport').addEventListener('click',closeImportModal);$('#importModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeImportModal()});
$('#inventoryFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#chooseFileButton strong').textContent='Leyendo archivo…';try{showImportPreview(await parseInventoryFile(file),file.name)}catch(error){alert(error.message)}finally{$('#chooseFileButton strong').textContent='Selecciona un Excel o CSV'}});
$('#confirmImport').addEventListener('click',async()=>{const valid=importRows.filter(row=>!row.errors.length).map(row=>row.product);if(!valid.length)return;$('#confirmImport').disabled=true;$('#confirmImport').textContent='Importando…';try{const result=await api('/products/bulk',{method:'POST',body:JSON.stringify({products:valid,mergeStrategy:$('#importStrategy').value})});products=await api('/products');populateCategories();render();closeImportModal();toast('Importación completada',`${result.created} creados y ${result.updated} actualizados.`)}catch(error){alert(error.message)}finally{$('#confirmImport').textContent='Importar productos'}});
$('#downloadTemplate').addEventListener('click',()=>{const headers=['SKU','Producto','Categoría','Color','Costo','Precio','Stock','Alerta','Descripción'];const example=['TEC-001','Producto ejemplo','Accesorios','Negro',100,150,10,3,'Descripción del producto'];const csv=[headers,example].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='plantilla-inventario-tecnoland.csv';a.click();URL.revokeObjectURL(a.href)});
$('#partnersNav').addEventListener('click',e=>{e.preventDefault();openUsersModal()});
$('#closeUsersModal').addEventListener('click',closeUsersModal);$('#cancelUserModal').addEventListener('click',closeUsersModal);$('#usersModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeUsersModal()});
$('#userForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/users',{method:'POST',body:JSON.stringify({fullName:$('#userFullName').value.trim(),username:$('#userUsername').value.trim(),password:$('#userPassword').value,role:$('#userRole').value})});$('#userForm').reset();await loadUsers();toast('Usuario creado','El socio ya puede iniciar sesión.') }catch(error){alert(error.message)}});
$('#usersList').addEventListener('click',async e=>{const toggle=e.target.closest('[data-toggle-user]');if(!toggle)return;try{await api('/users',{method:'PATCH',body:JSON.stringify({id:Number(toggle.dataset.toggleUser),active:toggle.textContent==='Desactivar'?false:true})});await loadUsers()}catch(error){alert(error.message)}})
$('#userCardButton')?.addEventListener('click',openPasswordModal);
$('#closePasswordModal').addEventListener('click',closePasswordModal);$('#cancelPasswordModal').addEventListener('click',closePasswordModal);$('#passwordModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closePasswordModal()});
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/users?route=me-password',{method:'PATCH',body:JSON.stringify({id:session.user.id,currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value})});closePasswordModal();toast('Contraseña actualizada','Tu acceso quedó renovado.')}catch(error){alert(error.message)}})
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const result=await fetch('/api/auth?route=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#loginUsername').value.trim(),password:$('#loginPassword').value})});const data=await result.json();if(!result.ok)throw new Error(data.error||'No se pudo iniciar sesión');setSession(data);hideLogin();await loadProducts();}catch(error){alert(error.message)}})
$('#inventoryNav').addEventListener('click',e=>{e.preventDefault();setSection('inventory')});
$('#ordersNav').addEventListener('click',e=>{e.preventDefault();openOrders()});
$('#backToInventory').addEventListener('click',()=>setSection('inventory'));
$('#openNewOrder').addEventListener('click',()=>{orderItems=[];$('#orderCustomerName').value='';$('#orderCustomerPhone').value='';$('#orderCustomerAddress').value='';$('#orderCustomerNote').value='';$('#orderInternalNote').value='';$('#orderCourierCompany').value='';$('#orderTrackingNumber').value='';$('#orderPaymentMethod').value='transfer';$('#orderStatus').value='pending';$('#orderDiscount').value=0;renderOrderForm()});
$('#openAllOrders').addEventListener('click',()=>{$('#allOrdersPanel').scrollIntoView({behavior:'smooth',block:'start'})});
$('#addOrderItem').addEventListener('click',openOrderItemModal);$('#closeOrderItemModal').addEventListener('click',closeOrderItemModal);$('#cancelOrderItemModal').addEventListener('click',closeOrderItemModal);$('#orderItemModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeOrderItemModal()});
$('#orderItemForm').addEventListener('submit',e=>{e.preventDefault();const product=products.find(item=>item.id===Number($('#orderItemProduct').value));const quantity=Math.max(1,Number($('#orderItemQuantity').value||1));if(!product)return;const currentQuantity=orderItems.find(item=>item.productId===product.id)?.quantity||0;const totalRequested=currentQuantity+quantity;if(totalRequested>product.stock){alert(`Solo hay ${product.stock} unidades disponibles de ${product.name}.`);return;}const existing=orderItems.find(item=>item.productId===product.id);if(existing){existing.quantity+=quantity;existing.subtotal=existing.quantity*existing.unitPrice;}else orderItems.push({productId:product.id,productName:product.name,sku:product.supplierSku||product.sku,unitPrice:product.price,unitCost:product.cost,quantity,subtotal:product.price*quantity});closeOrderItemModal();renderOrderForm();});
$('#orderItemsTable').addEventListener('click',e=>{const remove=e.target.closest('[data-order-remove]');if(!remove)return;orderItems.splice(Number(remove.dataset.orderRemove),1);renderOrderForm()});
$('#allOrdersTable').addEventListener('click',async e=>{const remove=e.target.closest('[data-order-delete]');if(!remove)return;const order=orders.find(item=>item.id===Number(remove.dataset.orderDelete));if(!order)return;if(!confirm(`Eliminar pedido ${order.orderNumber} y restaurar inventario?`))return;remove.disabled=true;try{await api(`/orders/${order.id}`,{method:'DELETE'});await loadProducts();await loadOrders();toast('Pedido eliminado','El inventario se restauró correctamente.')}catch(error){alert(error.message)}finally{remove.disabled=false}});
$('#ordersTable').addEventListener('click',async e=>{const remove=e.target.closest('[data-order-delete]');if(!remove)return;const order=orders.find(item=>item.id===Number(remove.dataset.orderDelete));if(!order)return;if(!confirm(`Eliminar pedido ${order.orderNumber} y restaurar inventario?`))return;remove.disabled=true;try{await api(`/orders/${order.id}`,{method:'DELETE'});await loadProducts();await loadOrders();toast('Pedido eliminado','El inventario se restauró correctamente.')}catch(error){alert(error.message)}finally{remove.disabled=false}});
['ordersSearch','ordersDateFrom','ordersDateTo'].forEach(id=>$('#'+id).addEventListener('input',()=>{orderFilters={query:$('#ordersSearch').value,from:$('#ordersDateFrom').value,to:$('#ordersDateTo').value};renderOrders()}));
$('#orderDiscount').addEventListener('input',renderOrderForm);
$('#confirmOrder').addEventListener('click',async e=>{e.preventDefault();try{const payload={customer:{name:$('#orderCustomerName').value.trim(),phone:$('#orderCustomerPhone').value.trim(),address:$('#orderCustomerAddress').value.trim(),note:$('#orderCustomerNote').value.trim()},items:orderItems.map(item=>({productId:item.productId,quantity:item.quantity,productName:item.productName,sku:item.sku})),discount:Number($('#orderDiscount').value||0),internalNote:$('#orderInternalNote').value.trim(),courierCompany:$('#orderCourierCompany').value.trim(),trackingNumber:$('#orderTrackingNumber').value.trim(),paymentMethod:$('#orderPaymentMethod').value,deliveryMethod:'courier',status:$('#orderStatus').value,courierHandoffAt:$('#orderCourierHandoffAt')?.value||null,estimatedDeliveryAt:$('#orderEstimatedDeliveryAt')?.value||null};await api('/orders',{method:'POST',body:JSON.stringify(payload)});orderItems=[];await loadProducts();openOrders();toast('Pedido creado','El inventario fue descontado.')}catch(error){alert(error.message)}})
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));loadProducts().catch(error=>{$('#productTable').innerHTML=`<tr><td colspan="9">No se pudo cargar la base de datos: ${error.message}</td></tr>`});
