const icons={grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',box:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><path d="m3.3 7 8.7 5 8.7-5M12 22V12"/>',bag:'<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4zM3 6h18M16 10a4 4 0 0 1-8 0"/>',truck:'<path d="M10 17h4V5H2v12h3m9-7h4l4 4v3h-3M7.5 20a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm9 0a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.09 14H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.63h.01A1.7 1.7 0 0 0 10 3.09V3a2 2 0 1 1 4 0v.09A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.37 9v.01A1.7 1.7 0 0 0 20.91 10H21a2 2 0 1 1 0 4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',wallet:'<path d="M20 7V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v12H5a3 3 0 0 1-3-3V6M16 13h2"/>',trend:'<path d="m3 17 6-6 4 4 8-8M14 7h7v7"/>',layers:'<path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 17l9 5 9-5"/>',alert:'<path d="M10.3 2.8 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.8a2 2 0 0 0-3.4 0ZM12 9v4M12 17h.01"/>',tag:'<path d="M20.6 13.6 11 23.2 1.8 14V2.8H13l7.6 7.6a2.3 2.3 0 0 1 0 3.2Z"/><circle cx="7" cy="8" r="1"/>',check:'<path d="m20 6-11 11-5-5"/>',spark:'<path d="m12 3-1.6 4.4L6 9l4.4 1.6L12 15l1.6-4.4L18 9l-4.4-1.6L12 3ZM5 16l-.8 2.2L2 19l2.2.8L5 22l.8-2.2L8 19l-2.2-.8L5 16Z"/>'};
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});

let products=[];
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',currencyDisplay:'narrowSymbol'}).format(n);
async function api(path,options={}){const response=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json'},...options});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'No fue posible guardar los cambios');return response.json()}
async function loadProducts(){
 const previous=JSON.parse(localStorage.getItem('tecnoland-products')||localStorage.getItem('novatech-products')||'null');
 if(previous?.length&&!localStorage.getItem('tecnoland-server-migration')){await api('/products/import',{method:'POST',body:JSON.stringify({products:previous})});localStorage.setItem('tecnoland-server-migration','completed')}
 products=await api('/products');populateCategories();render();
}

function populateCategories(){const current=$('#categoryFilter').value;const categories=[...new Set(products.map(p=>p.category))].sort();$('#categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+categories.map(c=>`<option value="${c}">${c}</option>`).join('');$('#categoryFilter').value=categories.includes(current)?current:'all'}
function filtered(){const q=$('#searchInput').value.toLowerCase().trim(),cat=$('#categoryFilter').value,status=$('#stockFilter').value;return products.filter(p=>{const match=!q||`${p.name} ${p.sku} ${p.category} ${p.productColor||''}`.toLowerCase().includes(q);const catMatch=cat==='all'||p.category===cat;const stockMatch=status==='all'||(status==='low'&&p.stock>0&&p.stock<=p.threshold)||(status==='available'&&p.stock>p.threshold)||(status==='out'&&p.stock===0);return match&&catMatch&&stockMatch})}
function render(){
 const totalCost=products.reduce((s,p)=>s+p.cost*p.stock,0),retail=products.reduce((s,p)=>s+p.price*p.stock,0),margin=retail-totalCost,units=products.reduce((s,p)=>s+p.stock,0),low=products.filter(p=>p.stock<=p.threshold).length;
 $('#inventoryCost').textContent=money(totalCost);$('#potentialMargin').textContent=money(margin);$('#marginPercent').textContent=`${retail?Math.round(margin/retail*100):0}% de rentabilidad estimada`;$('#totalUnits').textContent=units.toLocaleString();$('#lowStock').textContent=low;$('#retailValue').textContent=money(retail);$('#activeProducts').textContent=products.length;$('#navStockBadge').textContent=low;
 const list=filtered();$('#resultCount').textContent=`${list.length} producto${list.length===1?'':'s'} en el catálogo`;$('#footerCount').textContent=`Mostrando ${list.length} de ${products.length} productos`;$('#emptyState').hidden=list.length>0;
 $('#productTable').innerHTML=list.map(p=>{const unit=p.price-p.cost,percent=p.price?unit/p.price*100:0,isLow=p.stock<=p.threshold;return `<tr><td><div class="product-cell"><div class="product-thumb" style="--thumb:${p.themeColor||'#e8ecf5'}">${p.emoji||'📦'}</div><div class="product-info"><strong>${p.name}</strong><small>${p.sku}</small></div></div></td><td><span class="category-pill">${p.category}</span></td><td>${p.productColor||'Sin especificar'}</td><td>${money(p.cost)}</td><td class="price">${money(p.price)}</td><td><div class="margin"><strong>+${money(unit)}</strong><small>${percent.toFixed(1)}%</small></div></td><td><div class="stock-control ${isLow?'low':''}"><button data-adjust="-1" data-id="${p.id}" aria-label="Reducir stock">−</button><strong>${p.stock}</strong><button data-adjust="1" data-id="${p.id}" aria-label="Aumentar stock">+</button>${isLow?`<span class="stock-label">${p.stock?'BAJO':'AGOTADO'}</span>`:''}</div></td><td class="price">${money(p.cost*p.stock)}</td><td><button class="row-menu" data-edit="${p.id}" aria-label="Editar ${p.name}">•••</button></td></tr>`}).join('');
}
function openModal(product){$('#productForm').reset();$('#productId').value=product?.id||'';$('#modalTitle').textContent=product?'Editar producto':'Nuevo producto';if(product){$('#productName').value=product.name;$('#productSku').value=product.sku;$('#productCategory').value=product.category;$('#productColor').value=product.productColor||'';$('#productCost').value=product.cost;$('#productPrice').value=product.price;$('#productStock').value=product.stock;$('#productThreshold').value=product.threshold;$('#productDescription').value=product.description||''}else $('#productThreshold').value=5;updateFormMargin();$('#productModal').hidden=false;setTimeout(()=>$('#productName').focus(),20)}
function closeModal(){ $('#productModal').hidden=true }
function updateFormMargin(){const c=Number($('#productCost').value),p=Number($('#productPrice').value),m=p-c;$('#formMargin').textContent=`${money(m)} (${p?(m/p*100).toFixed(1):0}%)`}
function toast(){const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
$('#addProductButton').addEventListener('click',()=>openModal());$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);$('#productModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
['searchInput','categoryFilter','stockFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));['productCost','productPrice'].forEach(id=>$('#'+id).addEventListener('input',updateFormMargin));
$('#productTable').addEventListener('click',async e=>{const adjust=e.target.closest('[data-adjust]'),edit=e.target.closest('[data-edit]');if(adjust){adjust.disabled=true;try{const updated=await api(`/products/${adjust.dataset.id}/stock`,{method:'PATCH',body:JSON.stringify({adjustment:Number(adjust.dataset.adjust)})});const index=products.findIndex(p=>p.id===updated.id);products[index]=updated;render()}catch(error){alert(error.message)}}if(edit)openModal(products.find(x=>x.id===Number(edit.dataset.edit))) });
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#productId').value),existing=products.find(p=>p.id===id);const data={name:$('#productName').value.trim(),sku:$('#productSku').value.trim().toUpperCase(),category:$('#productCategory').value.trim(),productColor:$('#productColor').value.trim(),cost:Number($('#productCost').value),price:Number($('#productPrice').value),stock:Number($('#productStock').value),threshold:Number($('#productThreshold').value),description:$('#productDescription').value.trim(),emoji:existing?.emoji||'📦',themeColor:existing?.themeColor||'#e8ecf5'};try{const saved=await api(existing?`/products/${id}`:'/products',{method:existing?'PUT':'POST',body:JSON.stringify(data)});if(existing)products[products.findIndex(p=>p.id===id)]=saved;else products.unshift(saved);populateCategories();render();closeModal();toast()}catch(error){alert(error.message)}});
$('#exportButton').addEventListener('click',()=>{const rows=[['SKU','Producto','Categoría','Color','Costo (GTQ)','Precio (GTQ)','Stock'],...products.map(p=>[p.sku,p.name,p.category,p.productColor,p.cost,p.price,p.stock])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='inventario-tecnoland.csv';a.click();URL.revokeObjectURL(a.href)});
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));loadProducts().catch(error=>{$('#productTable').innerHTML=`<tr><td colspan="9">No se pudo cargar la base de datos: ${error.message}</td></tr>`});
