const icons={grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',box:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><path d="m3.3 7 8.7 5 8.7-5M12 22V12"/>',bag:'<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4zM3 6h18M16 10a4 4 0 0 1-8 0"/>',truck:'<path d="M10 17h4V5H2v12h3m9-7h4l4 4v3h-3M7.5 20a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm9 0a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.09 14H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.63h.01A1.7 1.7 0 0 0 10 3.09V3a2 2 0 1 1 4 0v.09A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.37 9v.01A1.7 1.7 0 0 0 20.91 10H21a2 2 0 1 1 0 4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',wallet:'<path d="M20 7V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v12H5a3 3 0 0 1-3-3V6M16 13h2"/>',trend:'<path d="m3 17 6-6 4 4 8-8M14 7h7v7"/>',layers:'<path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 17l9 5 9-5"/>',alert:'<path d="M10.3 2.8 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.8a2 2 0 0 0-3.4 0ZM12 9v4M12 17h.01"/>',tag:'<path d="M20.6 13.6 11 23.2 1.8 14V2.8H13l7.6 7.6a2.3 2.3 0 0 1 0 3.2Z"/><circle cx="7" cy="8" r="1"/>',check:'<path d="m20 6-11 11-5-5"/>',spark:'<path d="m12 3-1.6 4.4L6 9l4.4 1.6L12 15l1.6-4.4L18 9l-4.4-1.6L12 3ZM5 16l-.8 2.2L2 19l2.2.8L5 22l.8-2.2L8 19l-2.2-.8L5 16Z"/>',view:'<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6Z"/><circle cx="12" cy="12" r="2.5"/>'};
Object.assign(icons,{upload:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M17 8l-5-5-5 5M12 3v12"/>',edit:'<path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>'});
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});

const ORDER_DRAFT_KEY='tecnoland-order-draft';
const SESSION_KEY='tecnoland-session';
const orderDraftFields=['orderCustomerName','orderCustomerPhone','orderCustomerAddress','orderInternalNote','orderCourierCompany','orderTrackingNumber','orderPaymentMethod','orderStatus','orderCourierHandoffAt','orderEstimatedDeliveryAt','orderDiscount'];
const readJsonStorage=(storage,key)=>{try{return JSON.parse(storage.getItem(key)||'null')}catch{return null}};
const writeJsonStorage=(storage,key,value)=>storage.setItem(key,JSON.stringify(value));
const removeStorageKey=key=>{sessionStorage.removeItem(key);localStorage.removeItem(key)};
const migrateSessionFromLocalStorage=()=>{const stored=readJsonStorage(sessionStorage,SESSION_KEY);if(stored)return stored;const legacy=readJsonStorage(localStorage,SESSION_KEY);if(!legacy)return null;writeJsonStorage(sessionStorage,SESSION_KEY,legacy);localStorage.removeItem(SESSION_KEY);return legacy};
const migrateDraftFromLocalStorage=()=>{const stored=readJsonStorage(sessionStorage,ORDER_DRAFT_KEY);if(stored)return stored;const legacy=readJsonStorage(localStorage,ORDER_DRAFT_KEY);if(!legacy)return null;writeJsonStorage(sessionStorage,ORDER_DRAFT_KEY,legacy);localStorage.removeItem(ORDER_DRAFT_KEY);return legacy};
let products=[],importRows=[],users=[],orders=[],orderItems=[],session=migrateSessionFromLocalStorage(),productImages=[],productDraftSource=null,orderReceiptImage='',productSort={key:'createdAt',direction:'desc'},orderFilters={query:'',from:'',to:''},deliveryFilter='all',deliveryQuery='',photoViewerState={images:[],index:0},activeSection='inventory',pendingOrderSection=null,brandLogo=localStorage.getItem('tecnoland-brand-logo')||'';
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',currencyDisplay:'narrowSymbol'}).format(n);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const normalizeSearch=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const roleLabel=role=>role==='admin'?'Administrador':'Socio';
function userInitials(name='',username=''){const source=String(name||username||'TL').trim(),parts=source.split(/\s+/).filter(Boolean);return (parts.length>1?parts[0][0]+parts[1][0]:source.slice(0,2)).toUpperCase()}
function applyBrandLogo(){const nodes=[$('#brandMark'),$('#logoPreview')].filter(Boolean);nodes.forEach(node=>{node.classList.toggle('with-image',Boolean(brandLogo));node.innerHTML=brandLogo?`<img src="${escapeHtml(brandLogo)}" alt="Logo de Tecnoland">`:'N'});const remove=$('#removeLogoButton');if(remove)remove.disabled=!brandLogo}
function openSidebar(){$('#sidebar').classList.add('open');$('#sidebarBackdrop').classList.add('open');$('#menuButton').setAttribute('aria-expanded','true')}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false')}
function toggleSidebar(){$('#sidebar').classList.contains('open')?closeSidebar():openSidebar()}
function closeSidebarFromOutside(event){if(!$('#sidebar').classList.contains('open'))return;if(event.target.closest('#sidebar')||event.target.closest('#menuButton'))return;closeSidebar()}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const response=await fetch(`/api${path}`,{credentials:'same-origin',...options,headers});if(!response.ok){const error=new Error((await response.json().catch(()=>({}))).error||'No fue posible guardar los cambios');error.status=response.status;if(response.status===401){setSession(null);showLogin();error.message='Tu sesión expiró. Ingresa nuevamente para continuar.'}throw error}return response.json()}
const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function readApiWithRetry(path,attempts=3){let lastError;for(let attempt=1;attempt<=attempts;attempt+=1){try{return await api(path)}catch(error){lastError=error;const retryable=!error.status||error.status>=500;if(!retryable||attempt===attempts)throw error;setInventoryLoading(`Reconectando con el inventario… intento ${attempt+1} de ${attempts}`);await wait(attempt*900)}}throw lastError}
function applySessionUi(){const user=session?.user;$('#sessionName').textContent=user?.fullName||user?.username||'Tecnoland';$('#sessionRole').textContent=user?roleLabel(user.role):'Sin sesión';$('#sessionAvatar').textContent=userInitials(user?.fullName,user?.username);const isAdmin=user?.role==='admin';$('#partnersNav').hidden=!isAdmin;if(!isAdmin)closeUsersModal()}
function setSession(next){session=next; if(next)writeJsonStorage(sessionStorage,SESSION_KEY,next); else removeStorageKey(SESSION_KEY);applySessionUi()}
async function restoreSession(){try{const restored=await api('/auth/session');setSession(restored);hideLogin();return restored}catch{return null}}
function showLogin(){ $('#loginModal').hidden=false }
function hideLogin(){ $('#loginModal').hidden=true }
async function logout(){try{await api('/auth/logout',{method:'POST'})}catch{}setSession(null);products=[];orders=[];users=[];orderItems=[];setStockBadge();closeSidebar();closeModal();closeImportModal();closeUsersModal();closePasswordModal();closeOrderItemModal();closeOrderDetail();$('#loginForm').reset();showLogin();toast('Sesión cerrada','Vuelve a ingresar para continuar.')}
function setStockBadge(value=null){const badge=$('#navStockBadge');if(!badge)return;const count=Number(value);badge.hidden=!Number.isFinite(count)||count<=0;badge.textContent=badge.hidden?'':String(count)}
function setInventoryLoading(message='Cargando productos…'){setStockBadge();$('#emptyState').hidden=true;$('#resultCount').textContent=message;$('#footerCount').textContent='Conectando con la base de datos';$('#productTable').innerHTML=`<tr><td colspan="11"><div class="inventory-load-state"><span class="loading-spinner" aria-hidden="true"></span><div><strong>${escapeHtml(message)}</strong><small>Tu inventario permanece seguro mientras establecemos conexión.</small></div></div></td></tr>`}
function showInventoryLoadError(error){setStockBadge();if(error.status===401){$('#resultCount').textContent='Sesión expirada';$('#footerCount').textContent='Ingresa nuevamente para cargar el inventario';$('#productTable').innerHTML='<tr><td colspan="11"><div class="inventory-load-state error"><div><strong>Tu sesión expiró</strong><small>Ingresa nuevamente para continuar. Los datos no se han borrado.</small></div></div></td></tr>';return}$('#resultCount').textContent='No pudimos cargar el inventario';$('#footerCount').textContent='La conexión puede reintentarse';$('#productTable').innerHTML=`<tr><td colspan="11"><div class="inventory-load-state error"><div><strong>El inventario no está disponible en este momento</strong><small>${escapeHtml(error.message)}. Los datos no se han borrado.</small></div><button type="button" class="secondary-button" id="retryProducts">Reintentar</button></div></td></tr>`;$('#retryProducts').addEventListener('click',()=>loadProducts())}
async function loadProducts(){
 if(!session?.user){const restored=await restoreSession();if(!restored){showLogin();return}}
 setInventoryLoading();
 const previous=JSON.parse(localStorage.getItem('tecnoland-products')||localStorage.getItem('novatech-products')||'null');
 if(previous?.length&&!localStorage.getItem('tecnoland-server-migration')){await api('/products/import',{method:'POST',body:JSON.stringify({products:previous})});localStorage.setItem('tecnoland-server-migration','completed')}
 products=await readApiWithRetry('/products');populateCategories();render();
 if(session?.user?.role==='admin')await loadUsers().catch(()=>{});
 await loadOrders().catch(()=>{});
}
async function loadUsers(){users=await api('/users');renderUsers()}
async function loadOrders(){orders=await api('/orders');renderOrders();renderDeliveries();renderGlobalSearch()}
function renderUsers(){const list=$('#usersList');if(!list)return;list.innerHTML=users.map(user=>`<div class="user-row"><div><strong>${escapeHtml(user.fullName||user.full_name)}</strong><small>@${escapeHtml(user.username)} · ${escapeHtml(roleLabel(user.role))}</small></div><div class="user-row-actions"><select class="user-role-select" data-user-role="${user.id}" aria-label="Rol de ${escapeHtml(user.fullName||user.username)}"><option value="socio" ${user.role==='socio'?'selected':''}>Socio</option><option value="admin" ${user.role==='admin'?'selected':''}>Administrador</option></select><button class="secondary-button" data-toggle-user="${user.id}">${user.active?'Desactivar':'Activar'}</button></div></div>`).join('')||'<p>No hay usuarios.</p>'}
function openPhotoViewer(images,index=0,title='Vista ampliada'){const modal=$('#photoViewerModal'),img=$('#photoViewerImage'),heading=$('#photoViewerTitle');if(!modal||!img||!heading)return;photoViewerState={images,index};const current=images[index]||'';img.src=current;img.alt=title;heading.textContent=title;modal.hidden=false;updatePhotoViewerNav()}
function closePhotoViewer(){const modal=$('#photoViewerModal');if(modal)modal.hidden=true}
function updatePhotoViewerNav(){const prev=$('#photoViewerPrev'),next=$('#photoViewerNext');if(!prev||!next)return;const total=photoViewerState.images.length;prev.disabled=photoViewerState.index<=0;next.disabled=photoViewerState.index>=total-1}
function shiftPhotoViewer(step){const nextIndex=photoViewerState.index+step;if(nextIndex<0||nextIndex>=photoViewerState.images.length)return;photoViewerState.index=nextIndex;$('#photoViewerImage').src=photoViewerState.images[nextIndex];$('#photoViewerTitle').textContent=`Foto ${nextIndex+1} de ${photoViewerState.images.length}`;updatePhotoViewerNav()}
function renderPhotoPreview(filesOrUrls=[]){const grid=$('#photoPreviewGrid');if(!grid)return;grid.innerHTML=filesOrUrls.map((item,index)=>{const src=item.url||item;return `<figure class="photo-card"><img src="${escapeHtml(src)}" alt="Foto ${index+1}"><div class="photo-actions"><button type="button" class="photo-action" data-view-photo="${index}" aria-label="Ver foto"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg></button><button type="button" class="photo-action danger" data-remove-photo="${index}" aria-label="Eliminar foto">×</button></div></figure>`}).join('')||'<div class="photo-empty">Agrega imágenes para verlas aquí.</div>'}
function renderOrderProductPreview(product){const image=$('#orderProductPreviewImage'),name=$('#orderProductPreviewName'),meta=$('#orderProductPreviewMeta'),description=$('#orderProductPreviewDescription');if(!image||!name||!meta||!description)return;if(!product){image.textContent='📦';image.innerHTML='📦';name.textContent='Selecciona un producto';meta.textContent='Aquí verás SKU, categoría, color, precio y stock.';description.textContent='Esto ayuda a responder dudas del cliente antes de agregar el artículo al pedido.';return}const thumb=product.images?.[0]?.url||product.images?.[0]||'';image.className=`product-preview-image ${thumb?'with-image':''}`;image.innerHTML=thumb?`<img src="${escapeHtml(thumb)}" alt="${escapeHtml(product.name)}">`:(product.emoji||'📦');name.textContent=product.name;meta.textContent=`SKU prov. ${product.supplierSku||product.sku} · SKU int. ${product.internalSku||product.sku} · ${product.category} · ${product.productColor||'Sin especificar'} · ${money(product.price)} · stock ${product.stock}`;description.textContent=product.description||'Sin descripción adicional.'}
function getOrderDraft(){return{items:orderItems,fields:Object.fromEntries(orderDraftFields.map(id=>[id,$('#'+id)?.value||'']))}}
function hasOrderDraft(){const draft=getOrderDraft(),fields=draft.fields;return draft.items.length>0||orderDraftFields.some(id=>{const value=fields[id];if(id==='orderPaymentMethod')return value&&value!=='transfer';if(id==='orderStatus')return value&&value!=='pending';if(id==='orderDiscount')return Number(value)>0;return Boolean(value)})}
function saveOrderDraft(){if(hasOrderDraft())writeJsonStorage(sessionStorage,ORDER_DRAFT_KEY,getOrderDraft());else removeStorageKey(ORDER_DRAFT_KEY)}
function resetOrderDraft(){orderItems=[];const defaults={orderPaymentMethod:'transfer',orderStatus:'pending',orderDiscount:'0'};orderDraftFields.forEach(id=>{const field=$('#'+id);if(field)field.value=defaults[id]||''});removeStorageKey(ORDER_DRAFT_KEY);renderOrderForm()}
function restoreOrderDraft(){const stored=migrateDraftFromLocalStorage();if(!stored)return;orderItems=Array.isArray(stored.items)?stored.items:[];Object.entries(stored.fields||{}).forEach(([id,value])=>{const field=$('#'+id);if(field)field.value=value});renderOrderForm()}
function navigateToSection(section){activeSection=section;$('#inventorySection').hidden=section!=='inventory';$('#ordersSection').hidden=section!=='orders';$('#deliveriesSection').hidden=section!=='deliveries';$('#settingsSection').hidden=section!=='settings';$('#inventoryNav').classList.toggle('active',section==='inventory');$('#ordersNav').classList.toggle('active',section==='orders');$('#deliveriesNav').classList.toggle('active',section==='deliveries');$('#settingsNav').classList.toggle('active',section==='settings');closeSidebar();if(section==='orders'){restoreOrderDraft();renderOrderForm();loadOrders().catch(()=>{})}if(section==='deliveries'){renderDeliveries();loadOrders().catch(()=>{})}}
function setSection(section,{skipOrderGuard=false}={}){if(activeSection==='orders'&&section!=='orders'&&hasOrderDraft()&&!skipOrderGuard){pendingOrderSection=section;$('#orderLeaveModal').hidden=false;closeSidebar();return}navigateToSection(section)}
function openOrders(){setSection('orders')}
function openDeliveries(){setSection('deliveries')}
function openSettings(){setSection('settings')}
function openOrderCreateModal(){if(hasOrderDraft()&&!confirm('¿Deseas borrar el pedido actual y comenzar uno nuevo?'))return;resetOrderDraft();$('#orderCreateModal').hidden=false;setTimeout(()=>$('#orderCustomerName').focus(),20)}
function closeOrderCreateModal(){$('#orderCreateModal').hidden=true}
function orderProductMatches(product,query){const q=normalizeSearch(query.trim());return !q||normalizeSearch(`${product.name} ${product.sku} ${product.supplierSku||''} ${product.internalSku||''}`).includes(q)}
function renderOrderProductOptions(){const selected=$('#orderItemProduct'),search=$('#orderItemSearch'),panel=$('#orderItemSearchResults');if(!selected||!search||!panel)return;const availableProducts=products.filter(product=>product.active!==false&&product.stock>0&&orderProductMatches(product,search.value)).slice(0,12);panel.innerHTML=availableProducts.map(product=>{const thumb=product.images?.[0]?.url||product.images?.[0]||'';return `<button type="button" class="order-product-result ${String(product.id)===selected.value?'selected':''}" data-order-product-result="${product.id}"><span class="order-product-result-thumb">${thumb?`<img src="${escapeHtml(thumb)}" alt="${escapeHtml(product.name)}">`:escapeHtml(product.emoji||'📦')}</span><span class="order-product-result-copy"><strong>${escapeHtml(product.name)}</strong><small>SKU ${escapeHtml(product.internalSku||product.sku)} · ${escapeHtml(product.productColor||'Sin especificar')} · ${money(product.price)}</small></span><span class="order-product-result-stock">${product.stock} disp.</span></button>`}).join('')||'<div class="search-empty">No encontramos productos activos con stock.</div>';panel.hidden=false}
function selectOrderProduct(id){const product=products.find(item=>item.id===id);if(!product)return;$('#orderItemProduct').value=String(product.id);$('#orderItemSearch').value=product.name;$('#orderItemSearchResults').hidden=true;renderOrderProductPreview(product)}
function renderOrderForm(){$('#orderItemsTable').innerHTML=orderItems.map((item,index)=>{const product=products.find(p=>p.id===item.productId);return `<tr><td><strong>${escapeHtml(product?.name||item.productName)}</strong><small>SKU ${escapeHtml(product?.internalSku||product?.sku||item.sku)}</small></td><td><div class="order-quantity-editor"><button type="button" data-order-quantity-step="-1" data-order-index="${index}" aria-label="Restar una unidad">−</button><input class="order-quantity-input" data-order-quantity="${index}" type="number" min="1" max="${product?.stock||item.quantity}" value="${item.quantity}" aria-label="Cantidad de ${escapeHtml(product?.name||item.productName)}"><button type="button" data-order-quantity-step="1" data-order-index="${index}" aria-label="Sumar una unidad">+</button></div></td><td>${money(item.unitPrice)}</td><td>${money(item.subtotal)}</td><td><button class="row-action danger" data-order-remove="${index}" aria-label="Eliminar producto">×</button></td></tr>`}).join('')||'<tr><td colspan="5">Agrega productos al pedido.</td></tr>';const subtotal=orderItems.reduce((sum,item)=>sum+item.subtotal,0),cost=orderItems.reduce((sum,item)=>sum+item.unitCost*item.quantity,0),discount=Number($('#orderDiscount').value||0),total=Math.max(0,subtotal-discount),margin=total-cost;$('#orderProductCount').textContent=`${orderItems.length} item${orderItems.length===1?'':'s'} seleccionados`;$('#orderSubtotal').textContent=money(subtotal);$('#orderCost').textContent=money(cost);$('#orderMargin').textContent=money(margin);$('#orderTotal').textContent=money(total)}
function orderVisible(order){const q=normalizeSearch(orderFilters.query.trim());const created=new Date(order.createdAt);const from=orderFilters.from?new Date(`${orderFilters.from}T00:00:00`):null;const to=orderFilters.to?new Date(`${orderFilters.to}T23:59:59`):null;const match=!q||normalizeSearch(JSON.stringify(order)).includes(q);return match&&(!from||created>=from)&&(!to||created<=to)}
function renderOrders(){const visible=orders.filter(orderVisible),row=order=>`<tr><td><button type="button" class="delivery-order-link" data-view-order="${order.id}">${escapeHtml(order.orderNumber)}</button></td><td>${escapeHtml(order.customerName)}</td><td>${escapeHtml(order.status)}</td><td>${money(order.total)}</td><td>${money(order.marginTotal)}</td><td>${new Date(order.createdAt).toLocaleString('es-GT')}</td><td><button class="row-action danger" data-order-delete="${order.id}" aria-label="Eliminar pedido">Eliminar</button></td></tr>`;$('#allOrdersTable').innerHTML=visible.map(row).join('')||'<tr><td colspan="7">No hay pedidos con esos filtros.</td></tr>'}

function deliveryState(status){if(status==='delivered')return'delivered';if(status==='returned'||status==='cancelled')return'cancelled';return'transit'}
function deliveryStatusLabel(status){return({pending:'Pendiente',courier:'En tránsito',delivered:'Entregado',returned:'Cancelado',cancelled:'Cancelado'})[status]||status||'Pendiente'}
function deliveryStatusBadge(status){const state=deliveryState(status);return `<span class="delivery-status ${state}">${escapeHtml(deliveryStatusLabel(status))}</span>`}
function formatDeliveryDate(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString('es-GT',{day:'2-digit',month:'short',year:'numeric'})}
function renderDeliveries(){const table=$('#deliveriesTable');if(!table)return;const transit=orders.filter(order=>deliveryState(order.status)==='transit'),cancelled=orders.filter(order=>deliveryState(order.status)==='cancelled'),delivered=orders.filter(order=>deliveryState(order.status)==='delivered');$('#deliveryTotal').textContent=orders.length;$('#deliveryTransit').textContent=transit.length;$('#deliveryCancelled').textContent=cancelled.length;$('#deliveryDelivered').textContent=delivered.length;const query=normalizeSearch(deliveryQuery),visible=orders.filter(order=>(deliveryFilter==='all'||deliveryState(order.status)===deliveryFilter)&&(!query||normalizeSearch(JSON.stringify(order)).includes(query)));table.innerHTML=visible.map(order=>`<tr><td><button type="button" class="delivery-order-link" data-delivery-order="${order.id}">${escapeHtml(order.orderNumber)}</button></td><td><div class="delivery-client"><strong>${escapeHtml(order.customerName||'Sin cliente')}</strong><small>${escapeHtml(order.customerPhone||'Sin teléfono')}</small></div></td><td>${deliveryStatusBadge(order.status)}</td><td><div class="delivery-courier"><strong>${escapeHtml(order.courierCompany||'Sin empresa')}</strong><small>${escapeHtml(order.trackingNumber||'Sin tracking')}</small></div></td><td>${formatDeliveryDate(order.courierHandoffAt)}</td><td>${formatDeliveryDate(order.estimatedDeliveryAt)}</td></tr>`).join('')||'<tr><td colspan="6"><div class="search-empty">No hay entregas con estos filtros.</div></td></tr>';$('#deliveryFooter').textContent=`Mostrando ${visible.length} de ${orders.length} pedidos`}
async function openOrderDetail(id){
 const modal=$('#orderEditModal'),body=$('#orderEditBody');
 modal.hidden=false;$('#orderEditTitle').textContent='Cargando pedido…';body.innerHTML='<div class="search-empty">Cargando detalle…</div>';
 try{
  const order=await api(`/orders/${id}`);orderReceiptImage=order.receiptImageUrl||'';$('#orderEditTitle').textContent=`Pedido ${order.orderNumber}`;
  const items=(order.items||[]).map(item=>`<tr><td>${escapeHtml(item.sku)}</td><td>${escapeHtml(item.productName)}</td><td>${escapeHtml(item.productColor||'—')}</td><td>${item.quantity}</td><td>${money(item.unitPrice)}</td><td>${money(item.subtotal)}</td></tr>`).join('')||'<tr><td colspan="6">Sin artículos.</td></tr>';
  const statusOption=(value,label)=>`<option value="${value}" ${order.status===value?'selected':''}>${label}</option>`;
  const readOnlyCard=(label,value)=>`<div class="order-detail-card readonly" aria-readonly="true"><small>${label}<span>SOLO LECTURA</span></small><strong>${value}</strong></div>`;
  body.innerHTML=`<div class="order-detail-grid">${readOnlyCard('CLIENTE',escapeHtml(order.customerName))}<label class="order-detail-card editable-state"><small>ESTADO <span>EDITABLE</span></small><select id="orderUpdateStatus" form="orderUpdateForm" aria-label="Estado del pedido">${statusOption('pending','Pendiente de courier')}${statusOption('courier','En tránsito')}${statusOption('delivered','Entregado')}${statusOption('returned','Cancelado / devuelto')}</select><em>Selecciona el estado y guarda los cambios</em></label>${readOnlyCard('COURIER',escapeHtml(order.courierCompany||'Sin empresa'))}${readOnlyCard('TRACKING',escapeHtml(order.trackingNumber||'Sin tracking'))}${readOnlyCard('ENTREGADO A COURIER',formatDeliveryDate(order.courierHandoffAt))}${readOnlyCard('ENTREGA ESTIMADA',formatDeliveryDate(order.estimatedDeliveryAt))}${readOnlyCard('TELÉFONO',escapeHtml(order.customerPhone||'—'))}${readOnlyCard('FORMA DE PAGO',order.paymentMethod==='courier'?'Cobro por courier':'Transferencia')}</div><div class="order-detail-items"><table><thead><tr><th>SKU</th><th>PRODUCTO</th><th>COLOR</th><th>CANT.</th><th>UNITARIO</th><th>SUBTOTAL</th></tr></thead><tbody>${items}</tbody></table></div><div class="order-detail-total"><span>Total del pedido</span><strong>${money(order.total)}</strong></div><form class="order-update-form" id="orderUpdateForm" data-order-id="${order.id}"><h3>Actualizar entrega</h3><p class="order-update-help">Edita la información operativa y guarda todos los cambios, incluido el estado seleccionado arriba.</p><div class="order-update-form-grid">${order.paymentMethod==='courier'?`<label>Monto recibido por courier (Q)<input id="orderCourierAmount" type="number" min="0" step="0.01" value="${Number(order.courierAmountReceived||0)}" /></label>`:''}<label class="span-2">Información de la boleta<textarea id="orderReceiptInfo" rows="3" placeholder="Número, referencia u observaciones...">${escapeHtml(order.receiptInfo||'')}</textarea></label><label class="span-2">Foto de la boleta<input id="orderReceiptPhoto" type="file" accept="image/jpeg,image/png,image/webp" /></label><div class="receipt-preview span-2" id="orderReceiptPreview" ${orderReceiptImage?'':'hidden'}>${orderReceiptImage?`<img src="${escapeHtml(orderReceiptImage)}" alt="Boleta del pedido">`:''}</div></div><div class="modal-actions" style="margin-top:14px"><button type="submit" class="primary-button">Guardar cambios</button></div></form>`;
 }catch(error){$('#orderEditTitle').textContent='Detalle del pedido';body.innerHTML=`<div class="search-empty">${escapeHtml(error.message)}</div>`}
}
function renderOrderReceiptPreview(){const preview=$('#orderReceiptPreview');if(!preview)return;preview.hidden=!orderReceiptImage;preview.innerHTML=orderReceiptImage?`<img src="${escapeHtml(orderReceiptImage)}" alt="Boleta del pedido">`:''}
function closeOrderDetail(){$('#orderEditModal').hidden=true}
function closeOnBackdrop(selector,close){const modal=$(selector);let startedOnBackdrop=false;modal.addEventListener('pointerdown',event=>{startedOnBackdrop=event.target===modal});modal.addEventListener('pointerup',event=>{if(startedOnBackdrop&&event.target===modal)close();startedOnBackdrop=false});modal.addEventListener('pointercancel',()=>{startedOnBackdrop=false})}

function globalSearchGroup(title,items,renderItem){if(!items.length)return'';return `<div class="search-group-label">${title}</div>${items.map(renderItem).join('')}`}
function renderGlobalSearch(){const input=$('#searchInput'),panel=$('#globalSearchResults'),query=normalizeSearch(input.value.trim());if(!query){panel.hidden=true;input.setAttribute('aria-expanded','false');return}const productMatches=products.filter(product=>normalizeSearch(`${product.name} ${product.supplierSku||''} ${product.internalSku||product.sku||''}`).includes(query)).slice(0,6);const categories=[...new Set(products.map(product=>product.category).filter(Boolean))].filter(category=>normalizeSearch(category).includes(query)).slice(0,6);const orderMatches=orders.filter(order=>normalizeSearch(JSON.stringify(order)).includes(query)).slice(0,6);const customerMap=new Map();for(const order of orders){const key=normalizeSearch(`${order.customerName||''}::${order.customerPhone||''}`);if(!customerMap.has(key))customerMap.set(key,{name:order.customerName||'Sin nombre',phone:order.customerPhone||'',address:order.customerAddress||'',note:order.customerNote||'',orders:[]});customerMap.get(key).orders.push(order.orderNumber)}const customerMatches=[...customerMap.values()].filter(customer=>normalizeSearch(`${customer.name} ${customer.phone} ${customer.address} ${customer.note}`).includes(query)).slice(0,6);const resultButton=(kind,id,title,detail,icon,value='')=>`<button type="button" class="search-result" data-global-kind="${kind}" data-global-id="${escapeHtml(id)}" data-global-value="${escapeHtml(value)}"><span class="search-result-icon">${icon}</span><span class="search-result-copy"><strong>${escapeHtml(title)}</strong><small>${escapeHtml(detail)}</small></span></button>`;panel.innerHTML=globalSearchGroup('Productos',productMatches,product=>resultButton('product',product.id,product.name,`SKU ${product.internalSku||product.sku} · ${product.category}`,'P'))+globalSearchGroup('Categorías',categories,category=>resultButton('category','',category,`${products.filter(product=>product.category===category).length} productos`,'C',category))+globalSearchGroup('Pedidos',orderMatches,order=>resultButton('order',order.id,order.orderNumber,`${order.customerName} · ${order.status}`,'#',order.orderNumber))+globalSearchGroup('Clientes',customerMatches,customer=>resultButton('customer','',customer.name,`${customer.phone||'Sin teléfono'} · ${customer.orders.length} pedido${customer.orders.length===1?'':'s'}`,'CL',customer.name));if(!panel.innerHTML)panel.innerHTML='<div class="search-empty">No encontramos coincidencias.</div>';panel.hidden=false;input.setAttribute('aria-expanded','true')}
function closeGlobalSearch(){const panel=$('#globalSearchResults');panel.hidden=true;$('#searchInput').setAttribute('aria-expanded','false')}

function populateCategories(){const current=$('#categoryFilter').value;const categories=[...new Set(products.map(p=>p.category))].sort();$('#categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+categories.map(c=>`<option value="${c}">${c}</option>`).join('');$('#categoryFilter').value=categories.includes(current)?current:'all'}
function filtered(){const q=normalizeSearch($('#productSearch')?.value.trim()),cat=$('#categoryFilter').value,status=$('#stockFilter').value;return products.filter(p=>{const match=!q||normalizeSearch(`${p.name} ${p.sku} ${p.supplierSku||''} ${p.internalSku||''}`).includes(q);const catMatch=cat==='all'||p.category===cat,isActive=p.active!==false;const stockMatch=status==='all'||(status==='inactive'&&!isActive)||(status==='low'&&isActive&&p.stock>0&&p.stock<=p.threshold)||(status==='available'&&isActive&&p.stock>p.threshold)||(status==='out'&&isActive&&p.stock===0);return match&&catMatch&&stockMatch})}
function render(){ 
 const list=filtered(),sortedProducts=[...list].sort((a,b)=>{const key=productSort.key;const dir=productSort.direction==='asc'?1:-1;const value=(product)=>{if(key==='margin')return (product.price||0)-(product.cost||0);if(key==='inventoryValue')return (product.cost||0)*(product.stock||0);if(key==='supplierSku')return product.supplierSku||product.sku||'';if(key==='internalSku')return product.internalSku||product.sku||'';return product[key]??''};const av=value(a),bv=value(b);if(typeof av==='string'||typeof bv==='string')return String(av).localeCompare(String(bv),'es')*dir;return (av-bv)*dir;});
 const activeProducts=products.filter(p=>p.active!==false),totalCost=activeProducts.reduce((s,p)=>s+p.cost*p.stock,0),retail=activeProducts.reduce((s,p)=>s+p.price*p.stock,0),margin=retail-totalCost,units=activeProducts.reduce((s,p)=>s+p.stock,0),low=activeProducts.filter(p=>p.stock<=p.threshold).length;
 $('#inventoryCost').textContent=money(totalCost);$('#potentialMargin').textContent=money(margin);$('#marginPercent').textContent=`${retail?Math.round(margin/retail*100):0}% de rentabilidad estimada`;$('#totalUnits').textContent=units.toLocaleString();$('#lowStock').textContent=low;$('#retailValue').textContent=money(retail);$('#activeProducts').textContent=activeProducts.length;setStockBadge(low);$('#lowStockCard').disabled=low<=0;$('#lowStockCard').setAttribute('aria-label',low>0?`Filtrar ${low} producto${low===1?'':'s'} con bajo stock`:'No hay productos con bajo stock');
 $('#resultCount').textContent=`${list.length} producto${list.length===1?'':'s'} en el catálogo`;$('#footerCount').textContent=`Mostrando ${list.length} de ${products.length} productos`;$('#emptyState').hidden=list.length>0;
 $('#productTable').innerHTML=sortedProducts.map(p=>{const unit=p.price-p.cost,percent=p.price?unit/p.price*100:0,isActive=p.active!==false,isLow=isActive&&p.stock<=p.threshold,thumb=p.images?.[0]?.url||p.images?.[0]||'';return `<tr class="${isActive?'':'product-row-inactive'}"><td><button type="button" class="product-cell product-edit-trigger" data-edit="${p.id}" aria-label="Editar ${escapeHtml(p.name)}"><div class="product-thumb ${thumb?'with-image':''}" style="--thumb:${p.themeColor||'#e8ecf5'}">${thumb?`<img src="${escapeHtml(thumb)}" alt="${escapeHtml(p.name)}">`:escapeHtml(p.emoji||'📦')}</div><div class="product-info"><strong>${escapeHtml(p.name)}</strong>${isActive?'':'<span class="inactive-pill">INACTIVO</span>'}</div></button></td><td>${escapeHtml(p.supplierSku||p.sku)}</td><td>${escapeHtml(p.internalSku||p.sku)}</td><td><span class="category-pill">${escapeHtml(p.category)}</span></td><td>${escapeHtml(p.productColor||'Sin especificar')}</td><td>${money(p.cost)}</td><td class="price">${money(p.price)}</td><td><div class="margin"><strong>+${money(unit)}</strong><small>${percent.toFixed(1)}%</small></div></td><td>${p.stock}${isLow?` <span class="stock-label">${p.stock?'BAJO':'AGOTADO'}</span>`:''}</td><td class="price">${money(p.cost*p.stock)}</td><td><div class="row-actions"><button class="row-action" data-edit="${p.id}" aria-label="Editar ${escapeHtml(p.name)}"><span data-row-icon="edit"></span></button><button class="row-action danger" data-delete="${p.id}" aria-label="Eliminar ${escapeHtml(p.name)}"><span data-row-icon="trash"></span></button></div></td></tr>`}).join('');
 document.querySelectorAll('[data-row-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[el.dataset.rowIcon]}</svg>`});
}
function internalSkuPreview(){const supplier=$('#productSku').value.trim().toUpperCase(),color=$('#productColor').value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toUpperCase();$('#productInternalSku').value=supplier&&color?`${supplier}-${color}`:'Se generará automáticamente'}
function openModal(product,options={}){const copy=options.copy===true;$('#productForm').reset();$('#productId').value=copy?'':product?.id||'';productDraftSource=product||null;productImages=(product?.images||[]).map(image=>typeof image==='string'?image:image.url);$('#modalTitle').textContent=copy?'Copiar producto':product?'Editar producto':'Nuevo producto';if(product){$('#productName').value=product.name;$('#productSku').value=product.supplierSku||product.sku;$('#productCategory').value=product.category;$('#productColor').value=product.productColor||'';$('#productCost').value=product.cost;$('#productPrice').value=product.price;$('#productStock').value=product.stock;$('#productThreshold').value=product.threshold;$('#productDescription').value=product.description||''}else $('#productThreshold').value=5;const editing=Boolean(product&&!copy);$('#copyProductButton').hidden=!editing;$('#toggleProductActiveButton').hidden=!editing;$('#toggleProductActiveButton').textContent=product?.active===false?'Activar':'Desactivar';internalSkuPreview();renderPhotoPreview(productImages);updateFormMargin();$('#productModal').hidden=false;setTimeout(()=>{const target=copy?$('#productColor'):$('#productName');target.focus();if(copy)target.select()},20)}
function closeModal(){ $('#productModal').hidden=true }
function updateFormMargin(){const c=Number($('#productCost').value),p=Number($('#productPrice').value),m=p-c;$('#formMargin').textContent=`${money(m)} (${p?(m/p*100).toFixed(1):0}%)`}
function toast(title='Producto guardado',detail='El inventario se actualizó correctamente.'){const t=$('#toast');t.querySelector('strong').textContent=title;t.querySelector('small').textContent=detail;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function closeImportModal(){ $('#importModal').hidden=true;$('#inventoryFile').value='';importRows=[] }
function openUsersModal(){if(session?.user?.role!=='admin'){alert('Solo administradores pueden gestionar socios.');return}$('#usersModal').hidden=false; loadUsers().catch(error=>alert(error.message)) }
function closeUsersModal(){ $('#usersModal').hidden=true }
function openPasswordModal(){ $('#passwordModal').hidden=false }
function closePasswordModal(){ $('#passwordModal').hidden=true }
function openOrderItemModal(){$('#orderItemSearch').value='';$('#orderItemProduct').value='';$('#orderItemQuantity').value='1';renderOrderProductPreview(null);$('#orderItemModal').hidden=false;renderOrderProductOptions();setTimeout(()=>$('#orderItemSearch').focus(),20)}
function closeOrderItemModal(){ $('#orderItemModal').hidden=true }
function updateSortIndicators(){document.querySelectorAll('[data-sort]').forEach(th=>{th.dataset.active=th.dataset.sort===productSort.key?'true':'false'})}
const normalizeHeader=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases={sku:['sku','codigo','codigoproducto'],name:['producto','nombre','nombreproducto'],category:['categoria'],productColor:['color'],cost:['costo','costounitario','costogtq'],price:['precio','precioventa','pvp','preciogtq'],stock:['stock','cantidad','existencia'],threshold:['alerta','stockminimo','alertastockbajo'],description:['descripcion']};
function numericValue(value){if(typeof value==='number')return value;let text=String(value??'').replace(/[Q$\s]/g,'');if(text.includes(',')&&text.includes('.'))text=text.replaceAll(',','');else if(text.includes(','))text=text.replace(',','.');return Number(text)}
function valueByAlias(row,key){const found=Object.entries(row).find(([header])=>aliases[key].includes(normalizeHeader(header)));return found?.[1]??''}
async function readProductFiles(fileList){
 const files=[...fileList||[]].filter(file=>String(file.type||'').startsWith('image/'));
 if(!files.length)return [];
 return Promise.all(files.map(file=>new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})));
}
function isFileDrag(event){
 const types=[...event.dataTransfer?.types||[]];
 return types.includes('Files');
}
async function parseInventoryFile(file){
 if(file.size>5*1024*1024)throw new Error('El archivo supera el máximo de 5 MB.');
 let rawRows=[];
 if(file.name.toLowerCase().endsWith('.csv')){const rows=parseCsv(await file.text()),headers=rows.shift()||[];rawRows=rows.filter(row=>row.some(value=>String(value).trim())).map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]??''])))}
 else{if(!window.ExcelJS)throw new Error('No se pudo cargar el lector de Excel. Intenta nuevamente.');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)throw new Error('El Excel no contiene hojas.');const headers=sheet.getRow(1).values.slice(1).map(String);for(let rowNumber=2;rowNumber<=sheet.rowCount;rowNumber++){const values=sheet.getRow(rowNumber).values.slice(1).map(value=>value?.result??value?.text??value??'');if(values.some(value=>String(value).trim()))rawRows.push(Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])))} }
 if(!rawRows.length)throw new Error('El archivo no contiene productos.');if(rawRows.length>1000)throw new Error('El archivo supera el máximo de 1,000 productos.');
 const seen=new Set();return rawRows.map((row,index)=>{const product={sku:String(valueByAlias(row,'sku')).trim().toUpperCase(),name:String(valueByAlias(row,'name')).trim(),category:String(valueByAlias(row,'category')||'Sin categoría').trim(),productColor:String(valueByAlias(row,'productColor')||'Sin especificar').trim(),cost:numericValue(valueByAlias(row,'cost')),price:numericValue(valueByAlias(row,'price')),stock:numericValue(valueByAlias(row,'stock')),threshold:numericValue(valueByAlias(row,'threshold')||5),description:String(valueByAlias(row,'description')).trim()};const variantKey=`${product.sku}::${product.productColor.toLocaleLowerCase('es')}`,errors=[];if(!product.sku)errors.push('Falta SKU');if(!product.name)errors.push('Falta producto');for(const field of ['cost','price','stock','threshold'])if(!Number.isFinite(product[field])||product[field]<0)errors.push(`${field} inválido`);if(seen.has(variantKey)&&product.sku)errors.push('SKU y color duplicados');seen.add(variantKey);product.stock=Math.floor(product.stock);product.threshold=Math.floor(product.threshold);return {row:index+2,product,errors,action:products.some(item=>(item.supplierSku||item.sku)===product.sku&&(item.productColor||'Sin especificar').toLocaleLowerCase('es')===product.productColor.toLocaleLowerCase('es'))?'Actualizar':'Crear'}})}
function parseCsv(text){const rows=[];let row=[],value='',quoted=false;for(let index=0;index<text.length;index++){const char=text[index];if(char==='"'){if(quoted&&text[index+1]==='"'){value+='"';index+=1}else quoted=!quoted}else if(char===','&&!quoted){row.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[index+1]==='\n')index+=1;row.push(value);rows.push(row);row=[];value=''}else value+=char}if(value||row.length){row.push(value);rows.push(row)}if(rows[0]?.[0])rows[0][0]=rows[0][0].replace(/^\ufeff/,'');return rows}
function showImportPreview(rows,fileName){importRows=rows;const valid=rows.filter(row=>!row.errors.length),errors=rows.length-valid.length,updates=valid.filter(row=>row.action==='Actualizar').length;$('#previewSummary').innerHTML=`<span class="summary-pill">${escapeHtml(fileName)}</span><span class="summary-pill">${valid.length-updates} nuevos</span><span class="summary-pill">${updates} actualizaciones</span>${errors?`<span class="summary-pill error">${errors} con error</span>`:''}`;$('#previewTable').innerHTML=rows.slice(0,50).map(item=>`<tr><td>${item.row}</td><td>${escapeHtml(item.product.sku||'—')}</td><td>${escapeHtml(item.product.name||'—')}</td><td>${item.action}</td><td class="import-status ${item.errors.length?'error':'ok'}">${item.errors.length?escapeHtml(item.errors.join(', ')):'Lista'}</td></tr>`).join('');$('#importPreview').hidden=false;$('#confirmImport').disabled=!valid.length}
applyBrandLogo();
applySessionUi();
$('#addProductButton').addEventListener('click',()=>openModal());$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);closeOnBackdrop('#productModal',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSidebar();closeModal();closeImportModal();closeUsersModal();closePasswordModal();closeOrderItemModal();closeOrderDetail();hideLogin()}});
$('.main-nav').addEventListener('click',event=>{if(event.target.closest('.nav-item'))closeSidebar()});
['productSearch','categoryFilter','stockFilter'].forEach(id=>$('#'+id)?.addEventListener(id==='productSearch'?'input':'change',render));['productCost','productPrice'].forEach(id=>$('#'+id).addEventListener('input',updateFormMargin));
$('#searchInput').addEventListener('input',renderGlobalSearch);$('#searchInput').addEventListener('focus',renderGlobalSearch);$('#searchInput').addEventListener('keydown',event=>{if(event.key==='Escape')closeGlobalSearch()});
$('#lowStockCard').addEventListener('click',()=>{$('#productSearch').value='';$('#stockFilter').value='low';render();$('#productsPanel').scrollIntoView({behavior:'smooth',block:'start'})});
$('#globalSearchResults').addEventListener('click',event=>{const result=event.target.closest('[data-global-kind]');if(!result)return;const kind=result.dataset.globalKind,value=result.dataset.globalValue;$('#searchInput').value='';closeGlobalSearch();if(kind==='product'){setSection('inventory');const product=products.find(item=>item.id===Number(result.dataset.globalId));if(product)openModal(product);return}if(kind==='category'){setSection('inventory');$('#productSearch').value='';$('#categoryFilter').value=value;render();return}setSection('orders');$('#ordersSearch').value=value;orderFilters={...orderFilters,query:value};renderOrders();setTimeout(()=>$('#allOrdersPanel').scrollIntoView({behavior:'smooth',block:'start'}),50)});
document.addEventListener('click',event=>{if(!event.target.closest('.global-search'))closeGlobalSearch()});
['productSku','productColor'].forEach(id=>$('#'+id).addEventListener('input',internalSkuPreview));
$('#copyProductButton').addEventListener('click',()=>{const product=products.find(item=>item.id===Number($('#productId').value));if(product)openModal(product,{copy:true})});
$('#toggleProductActiveButton').addEventListener('click',async()=>{const id=Number($('#productId').value),product=products.find(item=>item.id===id);if(!product)return;const active=product.active===false;const button=$('#toggleProductActiveButton');button.disabled=true;try{const updated=await api(`/products/${id}/active`,{method:'PATCH',body:JSON.stringify({active})});products[products.findIndex(item=>item.id===id)]=updated;render();openModal(updated);toast(active?'Producto activado':'Producto desactivado',active?'Volverá a contar en métricas y pedidos nuevos.':'Ya no cuenta en métricas ni pedidos nuevos.')}catch(error){alert(error.message)}finally{button.disabled=false}});
$('#productTable').addEventListener('click',async e=>{const adjust=e.target.closest('[data-adjust]'),edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]');if(adjust){adjust.disabled=true;try{const updated=await api(`/products/${adjust.dataset.id}/stock`,{method:'PATCH',body:JSON.stringify({adjustment:Number(adjust.dataset.adjust)})});const index=products.findIndex(p=>p.id===updated.id);products[index]=updated;render()}catch(error){alert(error.message)}}if(edit)openModal(products.find(x=>x.id===Number(edit.dataset.edit)));if(remove){const product=products.find(x=>x.id===Number(remove.dataset.delete));if(confirm(`¿Eliminar “${product.name}”? Esta acción quedará registrada en el historial.`)){remove.disabled=true;try{await api(`/products/${product.id}`,{method:'DELETE'});products=products.filter(item=>item.id!==product.id);populateCategories();render();toast('Producto eliminado',`${product.name} se retiró del inventario.`)}catch(error){alert(error.message)}}}});
document.querySelectorAll('[data-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.sort;productSort={key,direction:productSort.key===key&&productSort.direction==='asc'?'desc':'asc'};updateSortIndicators();render()}));
$('#productPhotos').addEventListener('change',async e=>{const urls=await readProductFiles(e.target.files);if(urls.length){productImages=[...productImages,...urls];renderPhotoPreview(productImages)}e.target.value='';});
window.addEventListener('dragover',event=>{if(!isFileDrag(event))return;event.preventDefault()});
window.addEventListener('drop',event=>{if(!isFileDrag(event))return;if(event.target.closest('#photoDropzone'))return;event.preventDefault()});
['dragenter','dragover'].forEach(eventName=>$('#photoDropzone').addEventListener(eventName,event=>{if(!isFileDrag(event))return;event.preventDefault();event.stopPropagation();$('#photoDropzone').classList.add('dragging')}));
['dragleave','dragend'].forEach(eventName=>$('#photoDropzone').addEventListener(eventName,event=>{if(!isFileDrag(event))return;event.preventDefault();event.stopPropagation();if(eventName==='dragleave'&&event.currentTarget.contains(event.relatedTarget))return;$('#photoDropzone').classList.remove('dragging')}));
$('#photoDropzone').addEventListener('drop',async event=>{if(!isFileDrag(event))return;event.preventDefault();event.stopPropagation();$('#photoDropzone').classList.remove('dragging');const urls=await readProductFiles(event.dataTransfer?.files);if(!urls.length){alert('Arrastra archivos de imagen para cargarlos.');return}productImages=[...productImages,...urls];renderPhotoPreview(productImages)});
$('#photoPreviewGrid').addEventListener('click',e=>{const view=e.target.closest('[data-view-photo]'),remove=e.target.closest('[data-remove-photo]');if(view){openPhotoViewer(productImages.map(item=>item.url||item),Number(view.dataset.viewPhoto),`Foto ${Number(view.dataset.viewPhoto)+1}`);return}if(!remove)return;productImages=productImages.filter((_,index)=>index!==Number(remove.dataset.removePhoto));renderPhotoPreview(productImages);});
$('#closePhotoViewer').addEventListener('click',closePhotoViewer);closeOnBackdrop('#photoViewerModal',closePhotoViewer);$('#photoViewerPrev').addEventListener('click',()=>shiftPhotoViewer(-1));$('#photoViewerNext').addEventListener('click',()=>shiftPhotoViewer(1));
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#productId').value),existing=products.find(p=>p.id===id),base=existing||productDraftSource;const data={name:$('#productName').value.trim(),sku:$('#productSku').value.trim().toUpperCase(),category:$('#productCategory').value.trim(),productColor:$('#productColor').value.trim(),cost:Number($('#productCost').value),price:Number($('#productPrice').value),stock:Number($('#productStock').value),threshold:Number($('#productThreshold').value),description:$('#productDescription').value.trim(),emoji:base?.emoji||'📦',themeColor:base?.themeColor||'#e8ecf5',images:productImages};try{const saved=await api(existing?`/products/${id}`:'/products',{method:existing?'PUT':'POST',body:JSON.stringify(data)});if(existing)products[products.findIndex(p=>p.id===id)]=saved;else products.unshift(saved);populateCategories();render();closeModal();toast(existing?'Producto guardado':'Producto creado',existing?'El inventario se actualizó correctamente.':`Se generó el SKU interno ${saved.internalSku||saved.sku}.`)}catch(error){alert(error.message)}});
$('#exportButton').addEventListener('click',()=>{const rows=[['SKU','Producto','Categoría','Color','Costo (GTQ)','Precio (GTQ)','Stock'],...products.map(p=>[p.sku,p.name,p.category,p.productColor,p.cost,p.price,p.stock])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='inventario-tecnoland.csv';a.click();URL.revokeObjectURL(a.href)});
$('#importButton').addEventListener('click',()=>{$('#importModal').hidden=false;$('#importPreview').hidden=true;$('#confirmImport').disabled=true});$('#chooseFileButton').addEventListener('click',()=>$('#inventoryFile').click());$('#closeImportModal').addEventListener('click',closeImportModal);$('#cancelImport').addEventListener('click',closeImportModal);closeOnBackdrop('#importModal',closeImportModal);
$('#inventoryFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#chooseFileButton strong').textContent='Leyendo archivo…';try{showImportPreview(await parseInventoryFile(file),file.name)}catch(error){alert(error.message)}finally{$('#chooseFileButton strong').textContent='Selecciona un Excel o CSV'}});
$('#confirmImport').addEventListener('click',async()=>{const valid=importRows.filter(row=>!row.errors.length).map(row=>row.product);if(!valid.length)return;$('#confirmImport').disabled=true;$('#confirmImport').textContent='Importando…';try{const result=await api('/products/bulk',{method:'POST',body:JSON.stringify({products:valid,mergeStrategy:$('#importStrategy').value})});products=await api('/products');populateCategories();render();closeImportModal();toast('Importación completada',`${result.created} creados y ${result.updated} actualizados.`)}catch(error){alert(error.message)}finally{$('#confirmImport').textContent='Importar productos'}});
$('#downloadTemplate').addEventListener('click',()=>{const headers=['SKU','Producto','Categoría','Color','Costo','Precio','Stock','Alerta','Descripción'];const example=['TEC-001','Producto ejemplo','Accesorios','Negro',100,150,10,3,'Descripción del producto'];const csv=[headers,example].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='plantilla-inventario-tecnoland.csv';a.click();URL.revokeObjectURL(a.href)});
$('#partnersNav').addEventListener('click',e=>{e.preventDefault();closeSidebar();openUsersModal()});
$('#closeUsersModal').addEventListener('click',closeUsersModal);$('#cancelUserModal').addEventListener('click',closeUsersModal);closeOnBackdrop('#usersModal',closeUsersModal);
$('#userForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/users',{method:'POST',body:JSON.stringify({fullName:$('#userFullName').value.trim(),username:$('#userUsername').value.trim(),password:$('#userPassword').value,role:$('#userRole').value})});$('#userForm').reset();await loadUsers();toast('Usuario creado','El socio ya puede iniciar sesión.') }catch(error){alert(error.message)}});
$('#usersList').addEventListener('click',async e=>{const toggle=e.target.closest('[data-toggle-user]');if(!toggle)return;try{await api('/users',{method:'PATCH',body:JSON.stringify({id:Number(toggle.dataset.toggleUser),active:toggle.textContent==='Desactivar'?false:true})});await loadUsers()}catch(error){alert(error.message)}})
$('#usersList').addEventListener('change',async e=>{const role=e.target.closest('[data-user-role]');if(!role)return;try{await api('/users',{method:'PATCH',body:JSON.stringify({id:Number(role.dataset.userRole),role:role.value})});await loadUsers();toast('Rol actualizado','El acceso del usuario quedó actualizado.')}catch(error){alert(error.message);await loadUsers().catch(()=>{})}})
$('#userCardButton')?.addEventListener('click',openPasswordModal);
$('#logoutButton')?.addEventListener('click',()=>{logout()});
$('#closePasswordModal').addEventListener('click',closePasswordModal);$('#cancelPasswordModal').addEventListener('click',closePasswordModal);closeOnBackdrop('#passwordModal',closePasswordModal);
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/users?route=me-password',{method:'PATCH',body:JSON.stringify({id:session.user.id,currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value})});$('#passwordForm').reset();closePasswordModal();toast('Contraseña actualizada','Tu acceso quedó renovado.')}catch(error){alert(error.message)}})
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const result=await fetch('/api/auth?route=login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#loginUsername').value.trim(),password:$('#loginPassword').value})});const data=await result.json();if(!result.ok)throw new Error(data.error||'No se pudo iniciar sesión');setSession({user:data.user});hideLogin();await loadProducts();}catch(error){alert(error.message)}})
$('#inventoryNav').addEventListener('click',e=>{e.preventDefault();setSection('inventory')});
$('#ordersNav').addEventListener('click',e=>{e.preventDefault();openOrders()});
$('#deliveriesNav').addEventListener('click',e=>{e.preventDefault();openDeliveries()});
$('#settingsNav').addEventListener('click',e=>{e.preventDefault();openSettings()});
$('#changeLogoButton').addEventListener('click',()=>$('#logoFile').click());
$('#logoFile').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp','image/svg+xml'].includes(file.type)){alert('Selecciona una imagen JPG, PNG, WebP o SVG.');event.target.value='';return}if(file.size>1024*1024){alert('El logo no puede superar 1 MB.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>{brandLogo=reader.result;localStorage.setItem('tecnoland-brand-logo',brandLogo);applyBrandLogo();toast('Logo actualizado','La barra lateral ya muestra la nueva imagen.')};reader.readAsDataURL(file);event.target.value=''});
$('#removeLogoButton').addEventListener('click',()=>{brandLogo='';localStorage.removeItem('tecnoland-brand-logo');applyBrandLogo();toast('Logo eliminado','Volvimos al marcador de texto.')});
document.querySelectorAll('[data-delivery-filter]').forEach(button=>button.addEventListener('click',()=>{deliveryFilter=button.dataset.deliveryFilter;document.querySelectorAll('[data-delivery-filter]').forEach(item=>item.classList.toggle('active',item===button));renderDeliveries()}));
$('#deliverySearch').addEventListener('input',event=>{deliveryQuery=event.target.value;renderDeliveries()});
$('#deliveriesTable').addEventListener('click',event=>{const order=event.target.closest('[data-delivery-order]');if(order)openOrderDetail(Number(order.dataset.deliveryOrder))});
$('#closeOrderEditModal').addEventListener('click',closeOrderDetail);closeOnBackdrop('#orderEditModal',closeOrderDetail);
function closeOrderLeaveModal(){$('#orderLeaveModal').hidden=true;pendingOrderSection=null}
$('#closeOrderLeaveModal').addEventListener('click',closeOrderLeaveModal);closeOnBackdrop('#orderLeaveModal',closeOrderLeaveModal);
$('#saveOrderAndLeave').addEventListener('click',()=>{const destination=pendingOrderSection;saveOrderDraft();$('#orderLeaveModal').hidden=true;pendingOrderSection=null;if(destination)navigateToSection(destination)});
$('#discardOrderAndLeave').addEventListener('click',()=>{const destination=pendingOrderSection;resetOrderDraft();$('#orderLeaveModal').hidden=true;pendingOrderSection=null;if(destination)navigateToSection(destination)});
function closeOrderSuccessModal(){$('#orderSuccessModal').hidden=true}
$('#closeOrderSuccessModal').addEventListener('click',closeOrderSuccessModal);closeOnBackdrop('#orderSuccessModal',closeOrderSuccessModal);
$('#orderEditBody').addEventListener('change',event=>{if(event.target.id!=='orderReceiptPhoto')return;const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){alert('Selecciona una imagen JPG, PNG o WebP.');event.target.value='';return}if(file.size>2*1024*1024){alert('La foto de la boleta no puede superar 2 MB.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>{orderReceiptImage=reader.result;renderOrderReceiptPreview()};reader.readAsDataURL(file)});
$('#orderEditBody').addEventListener('submit',async event=>{const form=event.target.closest('#orderUpdateForm');if(!form)return;event.preventDefault();const button=form.querySelector('button[type="submit"]'),amount=$('#orderCourierAmount');button.disabled=true;try{const payload={status:$('#orderUpdateStatus').value,receiptInfo:$('#orderReceiptInfo').value.trim(),receiptImageUrl:orderReceiptImage};if(amount)payload.courierAmountReceived=Number(amount.value||0);const updated=await api(`/orders/${form.dataset.orderId}`,{method:'PATCH',body:JSON.stringify(payload)});const index=orders.findIndex(order=>order.id===updated.id);if(index>=0)orders[index]={...orders[index],...updated};renderOrders();renderDeliveries();renderGlobalSearch();toast('Pedido actualizado','Estado, cobro y boleta guardados.');await openOrderDetail(updated.id)}catch(error){alert(error.message)}finally{button.disabled=false}});
$('#backToInventory').addEventListener('click',()=>setSection('inventory'));
$('#openNewOrder').addEventListener('click',openOrderCreateModal);
$('#closeOrderCreateModal').addEventListener('click',closeOrderCreateModal);closeOnBackdrop('#orderCreateModal',closeOrderCreateModal);
$('#addOrderItem').addEventListener('click',openOrderItemModal);$('#closeOrderItemModal').addEventListener('click',closeOrderItemModal);$('#cancelOrderItemModal').addEventListener('click',closeOrderItemModal);closeOnBackdrop('#orderItemModal',closeOrderItemModal);$('#orderItemSearch').addEventListener('input',()=>{$('#orderItemProduct').value='';renderOrderProductPreview(null);renderOrderProductOptions()});$('#orderItemSearch').addEventListener('focus',renderOrderProductOptions);$('#orderItemSearchResults').addEventListener('click',event=>{const result=event.target.closest('[data-order-product-result]');if(result)selectOrderProduct(Number(result.dataset.orderProductResult))});document.addEventListener('click',event=>{if(!event.target.closest('.order-product-search'))$('#orderItemSearchResults').hidden=true});
$('#orderItemForm').addEventListener('submit',e=>{e.preventDefault();const product=products.find(item=>item.id===Number($('#orderItemProduct').value));const quantity=Math.max(1,Number($('#orderItemQuantity').value||1));if(!product)return;const currentQuantity=orderItems.find(item=>item.productId===product.id)?.quantity||0;const totalRequested=currentQuantity+quantity;if(totalRequested>product.stock){alert(`Solo hay ${product.stock} unidades disponibles de ${product.name}.`);return;}const existing=orderItems.find(item=>item.productId===product.id);if(existing){existing.quantity+=quantity;existing.subtotal=existing.quantity*existing.unitPrice;}else orderItems.push({productId:product.id,productName:product.name,sku:product.supplierSku||product.sku,unitPrice:product.price,unitCost:product.cost,quantity,subtotal:product.price*quantity});closeOrderItemModal();renderOrderForm();saveOrderDraft()});
function updateOrderItemQuantity(index,quantity){const item=orderItems[index],product=products.find(entry=>entry.id===item?.productId);if(!item)return;const next=Math.max(1,Math.floor(Number(quantity)||1)),available=product?.stock||next;if(next>available){alert(`Solo hay ${available} unidades disponibles de ${product?.name||item.productName}.`);renderOrderForm();return}item.quantity=next;item.subtotal=item.unitPrice*next;renderOrderForm();saveOrderDraft()}
$('#orderItemsTable').addEventListener('click',e=>{const remove=e.target.closest('[data-order-remove]');if(remove){orderItems.splice(Number(remove.dataset.orderRemove),1);renderOrderForm();saveOrderDraft();return}const step=e.target.closest('[data-order-quantity-step]');if(step){const index=Number(step.dataset.orderIndex);updateOrderItemQuantity(index,orderItems[index].quantity+Number(step.dataset.orderQuantityStep))}});
$('#orderItemsTable').addEventListener('change',e=>{const input=e.target.closest('[data-order-quantity]');if(input)updateOrderItemQuantity(Number(input.dataset.orderQuantity),input.value)});
$('#allOrdersTable').addEventListener('click',async e=>{const view=e.target.closest('[data-view-order]');if(view){openOrderDetail(Number(view.dataset.viewOrder));return}const remove=e.target.closest('[data-order-delete]');if(!remove)return;const order=orders.find(item=>item.id===Number(remove.dataset.orderDelete));if(!order)return;if(!confirm(`Eliminar pedido ${order.orderNumber} y restaurar inventario?`))return;remove.disabled=true;try{await api(`/orders/${order.id}`,{method:'DELETE'});await loadProducts();await loadOrders();toast('Pedido eliminado','El inventario se restauró correctamente.')}catch(error){alert(error.message)}finally{remove.disabled=false}});
['ordersSearch','ordersDateFrom','ordersDateTo'].forEach(id=>$('#'+id).addEventListener('input',()=>{orderFilters={query:$('#ordersSearch').value,from:$('#ordersDateFrom').value,to:$('#ordersDateTo').value};renderOrders()}));
orderDraftFields.forEach(id=>$('#'+id)?.addEventListener('input',()=>{if(id==='orderDiscount')renderOrderForm();saveOrderDraft()}));
$('#cancelOrder').addEventListener('click',closeOrderCreateModal);
window.addEventListener('beforeunload',event=>{if(!hasOrderDraft())return;saveOrderDraft();event.preventDefault();event.returnValue='' });
$('#confirmOrder').addEventListener('click',async e=>{e.preventDefault();const button=e.currentTarget;button.disabled=true;try{const payload={customer:{name:$('#orderCustomerName').value.trim(),phone:$('#orderCustomerPhone').value.trim(),address:$('#orderCustomerAddress').value.trim()},items:orderItems.map(item=>({productId:item.productId,quantity:item.quantity,productName:item.productName,sku:item.sku})),discount:Number($('#orderDiscount').value||0),internalNote:$('#orderInternalNote').value.trim(),courierCompany:$('#orderCourierCompany').value.trim(),trackingNumber:$('#orderTrackingNumber').value.trim(),paymentMethod:$('#orderPaymentMethod').value,deliveryMethod:'courier',status:$('#orderStatus').value,courierHandoffAt:$('#orderCourierHandoffAt')?.value||null,estimatedDeliveryAt:$('#orderEstimatedDeliveryAt')?.value||null};const created=await api('/orders',{method:'POST',body:JSON.stringify(payload)});resetOrderDraft();closeOrderCreateModal();$('#createdOrderNumber').textContent=created.orderNumber;$('#orderSuccessModal').hidden=false;loadProducts().then(openOrders).catch(showInventoryLoadError)}catch(error){alert(error.message)}finally{button.disabled=false}})
$('#sidebarBackdrop').addEventListener('click',closeSidebar);
document.addEventListener('pointerdown',closeSidebarFromOutside);
$('#menuButton').addEventListener('click',toggleSidebar);loadProducts().catch(showInventoryLoadError);
