const { Pool } = require('pg');
const seedProducts = require('../data/seed-products.json');
const { createPasswordHash, slugify } = require('./security');

const connectionString = process.env.POSTGRES_URL || process.env.POSTGRES_URL_NON_POOLING;
if (!connectionString) throw new Error('Falta POSTGRES_URL para conectar con Supabase.');
const databaseUrl = new URL(connectionString);
databaseUrl.searchParams.delete('sslmode');

const pool = new Pool({
  connectionString: databaseUrl.toString(),
  ssl: { rejectUnauthorized: false },
  max: 3,
  idleTimeoutMillis: 10000
});

async function ensureDatabase() {
  await pool.query(`
    create table if not exists products (
      id bigint primary key generated by default as identity,
      name text not null,
      sku text not null unique,
      supplier_sku text not null default '',
      internal_sku text not null default '',
      category text not null,
      product_color text not null default 'Sin especificar',
      cost numeric(12,2) not null default 0,
      price numeric(12,2) not null default 0,
      stock integer not null default 0 check (stock >= 0),
      threshold integer not null default 0 check (threshold >= 0),
      description text not null default '',
      emoji text not null default '📦',
      theme_color text not null default '#e8ecf5',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create table if not exists inventory_history (
      id bigint primary key generated always as identity,
      product_id bigint references products(id) on delete set null,
      sku text,
      action text not null,
      details jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now()
    );
    create index if not exists inventory_history_product_id_idx on inventory_history(product_id);
    create index if not exists inventory_history_created_at_idx on inventory_history(created_at desc);
    create table if not exists product_images (
      id bigint primary key generated by default as identity,
      product_id bigint not null references products(id) on delete cascade,
      image_url text not null,
      sort_order integer not null default 0,
      created_at timestamptz not null default now()
    );
    create index if not exists product_images_product_id_idx on product_images(product_id, sort_order, id);
    create table if not exists users (
      id bigint primary key generated by default as identity,
      full_name text not null,
      username text not null unique,
      role text not null default 'socio',
      password_salt text not null,
      password_hash text not null,
      active boolean not null default true,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create table if not exists orders (
      id bigint primary key generated by default as identity,
      order_number text not null unique,
      created_by_user_id bigint references users(id) on delete set null,
      customer_name text not null,
      customer_phone text not null default '',
      customer_address text not null default '',
      customer_note text not null default '',
      internal_note text not null default '',
      courier_company text not null default '',
      tracking_number text not null default '',
      delivery_method text not null default 'courier',
      payment_method text not null default 'transfer',
      status text not null default 'pending',
      subtotal numeric(12,2) not null default 0,
      discount numeric(12,2) not null default 0,
      total numeric(12,2) not null default 0,
      cost_total numeric(12,2) not null default 0,
      margin_total numeric(12,2) not null default 0,
      courier_handoff_at timestamptz,
      estimated_delivery_at timestamptz,
      delivered_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create table if not exists order_items (
      id bigint primary key generated by default as identity,
      order_id bigint not null references orders(id) on delete cascade,
      product_id bigint references products(id) on delete set null,
      sku text not null,
      product_name text not null,
      product_color text not null default '',
      quantity integer not null check (quantity > 0),
      unit_cost numeric(12,2) not null default 0,
      unit_price numeric(12,2) not null default 0,
      subtotal numeric(12,2) not null default 0
    );
    create index if not exists orders_created_at_idx on orders(created_at desc);
    create index if not exists order_items_order_id_idx on order_items(order_id);
  `);
  await pool.query(`alter table products add column if not exists supplier_sku text not null default ''`);
  await pool.query(`alter table products add column if not exists internal_sku text not null default ''`);
  await pool.query(`update products set supplier_sku = case when supplier_sku = '' then sku else supplier_sku end where supplier_sku = ''`);
  await pool.query(`update products set internal_sku = case when internal_sku = '' then sku else internal_sku end where internal_sku = ''`);
  await pool.query(`update products set sku = internal_sku where internal_sku <> '' and sku <> internal_sku`);

  const { rows: [{ count }] } = await pool.query('select count(*)::int as count from products');
  if (count === 0) {
    const client = await pool.connect();
    try {
      await client.query('begin');
      for (const product of seedProducts) {
        const supplierSku = product.sku;
        const internalSku = `${supplierSku}-${slugify(product.productColor || 'general')}`.toUpperCase();
        await client.query(
          `insert into products (id,name,sku,supplier_sku,internal_sku,category,product_color,cost,price,stock,threshold,description,emoji,theme_color)
           values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) on conflict (sku) do nothing`,
          [product.id, product.name, internalSku, supplierSku, internalSku, product.category, product.productColor, product.cost, product.price, product.stock, product.threshold, product.description, product.emoji, product.themeColor]
        );
      }
      await client.query("select setval(pg_get_serial_sequence('products','id'), greatest((select max(id) from products), 1))");
      await client.query("insert into inventory_history (product_id,sku,action,details) select id,sku,'initial_seed',jsonb_build_object('stock',stock) from products");
      await client.query('commit');
    } catch (error) {
      await client.query('rollback');
      throw error;
    } finally {
      client.release();
    }
  }

  const { rows: [{ count: userCount }] } = await pool.query('select count(*)::int as count from users');
  if (userCount === 0) {
    const adminPassword = process.env.TECNOLAND_ADMIN_PASSWORD || 'Admin12345!';
    const { salt, hash } = createPasswordHash(adminPassword);
    await pool.query(
      `insert into users (full_name, username, role, password_salt, password_hash)
       values ($1,$2,$3,$4,$5)`,
      ['Administrador Tecnoland', 'admin', 'admin', salt, hash]
    );
  }
}

const mapProduct = row => ({
  id: Number(row.id), name: row.name, sku: row.sku, category: row.category,
  supplierSku: row.supplier_sku || row.sku, internalSku: row.internal_sku || row.sku,
  productColor: row.product_color, cost: Number(row.cost), price: Number(row.price),
  stock: row.stock, threshold: row.threshold, description: row.description,
  emoji: row.emoji, themeColor: row.theme_color, updatedAt: row.updated_at
});

const productValues = value => [
  String(value.name || '').trim(), String(value.sku || '').trim().toUpperCase(),
  String(value.category || '').trim(), String(value.productColor || 'Sin especificar').trim(),
  Number(value.cost || 0), Number(value.price || 0), Math.max(0, Number(value.stock || 0)),
  Math.max(0, Number(value.threshold || 0)), String(value.description || '').trim(),
  value.emoji || '📦', value.themeColor || '#e8ecf5'
];

function buildInternalSku(supplierSku, productColor) {
  return `${String(supplierSku || '').trim().toUpperCase()}-${slugify(productColor || 'general')}`.replace(/-+/g, '-').toUpperCase();
}

module.exports = { pool, ensureDatabase, mapProduct, productValues, buildInternalSku };
