const { Pool } = require('pg');
const seedProducts = require('../data/seed-products.json');
const { createPasswordHash } = require('./security');

const connectionString = process.env.POSTGRES_URL || process.env.POSTGRES_URL_NON_POOLING;
if (!connectionString) throw new Error('Falta POSTGRES_URL para conectar con Supabase.');
const databaseUrl = new URL(connectionString);
databaseUrl.searchParams.delete('sslmode');

const pool = new Pool({
  connectionString: databaseUrl.toString(),
  ssl: { rejectUnauthorized: false },
  max: 3,
  idleTimeoutMillis: 10000
});

async function ensureDatabase() {
  await pool.query(`
    create table if not exists products (
      id bigint primary key generated by default as identity,
      name text not null,
      sku text not null unique,
      category text not null,
      product_color text not null default 'Sin especificar',
      cost numeric(12,2) not null default 0,
      price numeric(12,2) not null default 0,
      stock integer not null default 0 check (stock >= 0),
      threshold integer not null default 0 check (threshold >= 0),
      description text not null default '',
      emoji text not null default '📦',
      theme_color text not null default '#e8ecf5',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create table if not exists inventory_history (
      id bigint primary key generated always as identity,
      product_id bigint references products(id) on delete set null,
      sku text,
      action text not null,
      details jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now()
    );
    create index if not exists inventory_history_product_id_idx on inventory_history(product_id);
    create index if not exists inventory_history_created_at_idx on inventory_history(created_at desc);
    create table if not exists users (
      id bigint primary key generated by default as identity,
      full_name text not null,
      username text not null unique,
      role text not null default 'socio',
      password_salt text not null,
      password_hash text not null,
      active boolean not null default true,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
  `);

  const { rows: [{ count }] } = await pool.query('select count(*)::int as count from products');
  if (count === 0) {
    const client = await pool.connect();
    try {
      await client.query('begin');
      for (const product of seedProducts) {
        await client.query(
          `insert into products (id,name,sku,category,product_color,cost,price,stock,threshold,description,emoji,theme_color)
           values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) on conflict (sku) do nothing`,
          [product.id, product.name, product.sku, product.category, product.productColor, product.cost, product.price, product.stock, product.threshold, product.description, product.emoji, product.themeColor]
        );
      }
      await client.query("select setval(pg_get_serial_sequence('products','id'), greatest((select max(id) from products), 1))");
      await client.query("insert into inventory_history (product_id,sku,action,details) select id,sku,'initial_seed',jsonb_build_object('stock',stock) from products");
      await client.query('commit');
    } catch (error) {
      await client.query('rollback');
      throw error;
    } finally {
      client.release();
    }
  }

  const { rows: [{ count: userCount }] } = await pool.query('select count(*)::int as count from users');
  if (userCount === 0) {
    const adminPassword = process.env.TECNOLAND_ADMIN_PASSWORD || 'Admin12345!';
    const { salt, hash } = createPasswordHash(adminPassword);
    await pool.query(
      `insert into users (full_name, username, role, password_salt, password_hash)
       values ($1,$2,$3,$4,$5)`,
      ['Administrador Tecnoland', 'admin', 'admin', salt, hash]
    );
  }
}

const mapProduct = row => ({
  id: Number(row.id), name: row.name, sku: row.sku, category: row.category,
  productColor: row.product_color, cost: Number(row.cost), price: Number(row.price),
  stock: row.stock, threshold: row.threshold, description: row.description,
  emoji: row.emoji, themeColor: row.theme_color, updatedAt: row.updated_at
});

const productValues = value => [
  String(value.name || '').trim(), String(value.sku || '').trim().toUpperCase(),
  String(value.category || '').trim(), String(value.productColor || 'Sin especificar').trim(),
  Number(value.cost || 0), Number(value.price || 0), Math.max(0, Number(value.stock || 0)),
  Math.max(0, Number(value.threshold || 0)), String(value.description || '').trim(),
  value.emoji || '📦', value.themeColor || '#e8ecf5'
];

module.exports = { pool, ensureDatabase, mapProduct, productValues };
